### PR TITLE
12 new logos for OH Add-Ons page on website

### PR DESCRIPTION
**Pull request by bracklanna**
12 additional icons to fill in blank place-holders on the current OH2 Add-Ons web page at [https://www.openhab.org/addons/](https://www.openhab.org/addons/) .

Hopefully this time around I've gotten the PR location correct. If this works properly I'll do another PR for the `master` branch shortly.

### CODE REVIEW

**Comment by bracklanna** [comment]
I meant these icons to appear on this page:
https://www.openhab.org/addons/

When I look at the deploy-preview website it doesn't look like the intended location is right?:
https://deploy-preview-1158--openhab-docs-preview.netlify.com

**Comment by ghys** [comment]
Yes, the preview builds do not include the add-on pages, it would take forever to build. LGTM, could you add a signoff line so I can include it in the merged commit? Thanks!

**Comment by bracklanna** [comment]
Signed-off-by: bracklanna <bracklanna@users.noreply.github.com>

**Comment by bracklanna** [comment]
> Yes, the preview builds do not include the add-on pages, it would take forever to build. LGTM, could you add a signoff line so I can include it in the merged commit? Thanks!

I'm new to github. I hope I've put the sign-off in the right place (at the end of my commit). I attempted to get the DCO bot to re-review by closing & re-opening the PR but it's not "taking".

**Comment by ghys** [comment]
Sorry about the sign-off rule, but - basically - it's necessary for us to know in some way that you're not contributing on your employer's dime without their consent, or stealing someone else's work (by signing off you agree to https://developercertificate.org/) - it's important to us to be in the clear legally. I'll waive it this time, I suppose.

**Comment by bracklanna** [comment]
> Sorry about the sign-off rule, but - basically - it's necessary for us to know...

I have no problem with doing a sign-off, I just don't understand the exact mechanics of how to do it. Where is the sign-off line supposed to go? I tried putting it in a comment in my original commit in my fork of the repo AFTER I committed (and then opened this PR.)

In future will it work correctly if I put the sign-off line as a comment at the end of my commit, in my repo, BEFORE I commit in my repo?

Thanks for your time/help explaining this simple matter.

**Comment by ghys** [comment]
if you're using git (the commandline tool) you have to configure your name and email
```
git config user.name "Your Full Name"
git config user.email "your@email.com"
```
then you use the `-s` flag when committing with `git commit` and the line will be added.

If you're contributing directly on the GitHub website, just add the line manually in the description field.

**Comment by bracklanna** [comment]
I'm using the website, that's why I don't have the option to amend. 
I'll try adding a sign-off in the description field of the commit in my fork before I open the next PR.
Thanks.

**Comment by ghys** [comment]
Sure, don't worry about DCO, it's just a tool, as long as we can find a signoff we can include to the final commit we're good.

**Comment by Confectrician** [comment]
Hey @bracklanna 

I have written a Tutorial about signing-off especially with a part for web editor, since this is a regularly question here.

https://community.openhab.org/t/dco-check-signing-off-with-github-web-editor-explanation/83330?u=confectrician

If there are any additional questions feel free to ping me.

**Comment by bracklanna** [comment]
I found that article independently, thanks, a couple of hours ago. Very helpful.
As far as getting these images in, whatever you think is best, cherry-picking or merging the second, later PR I submitted to `master`.

In future I will be sure to properly sign-off all commits.

**Pull request merged**
