### PR TITLE
Condense add-ons tables by reining in h4; top align cells

### PR DESCRIPTION
**Pull request by watou**
condensed

The only other opportunity to further condense the list vertically is to strip off the paragraph tag around the markdownify'd description.

Signed-off-by: John Cocula <john@cocula.com>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Thanks - lgtm, definitely an improvement.

**Comment by ThomDietrich** [comment]
Oh... May I suggest to remove all ":before" attributes and adding this inside openhab.css?

```
.addon-table h4 {
    margin: 0px 0px 5px;
.addon-table td {
    vertical-align: top;
}
```

**Comment by watou** [comment]
OK, I will try that and update the PR.

**Comment by watou** [comment]
Please review and merge if OK.  Thanks very much, @ThomDietrich and for reviewing the last PR!

condensed2

**Comment by kaikreuzer** [comment]
Thanks @watou!

**Pull request merged**
