### PR TITLE
Update OLA links

### PR DESCRIPTION
**Pull request by peternewman**

### CODE REVIEW

**Comment by ThomDietrich** [comment]
Hello @peternewman,

Thanks for your contribution! However, please check the fith line of the file :wink:

**Comment by watou** [comment]
[This](https://github.com/openhab/openhab1-addons/blob/master/bundles/binding/org.openhab.binding.dmx/README.md) is the file you want to edit, @peternewman.  Thanks!

**Comment by peternewman** [comment]
Oops, see https://github.com/openhab/openhab1-addons/issues/5094 instead.

Can I suggest doing something like this too https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/ . I was going to suggest extending CONTRIBUTING.md but it doesn't seem to be as visible as it once was.

I think https://github.com/openhab/openhab-docs/blob/gh-pages/README.md#contributing-to-the-documentation could be made a bit clearer, perhaps by moving https://github.com/openhab/openhab-docs/blob/gh-pages/README.md#automatically-generated-parts or a subset up closer to that.

**Comment by ThomDietrich** [comment]
That's a good suggestion. I'll look into it. Thanks!

**Pull request closed without merging**
