### PR TITLE
Sign-off-by: Brad Gilmer <brad@gilmer.tv> (github: bgilmer77)

### PR DESCRIPTION
**Pull request by bgilmer77**
This is a test pull request with one change.  Please DO not accept the PR, but instead, please delete it. @ThomDietrich, after my experience loosing many hours of work on the GitHub website, I am trying GitHub Desktop.  Less chance to loose the work, but of course, another learning curve.

### CODE REVIEW

**Comment by bgilmer77** [comment]
@ThomDietrich @LightIsLife I would appreciate your help.  Long story short, after four hours of editing, I lost all my work using the GitHub website and directly editing the Items.md file.  After taking a few hours to walk around the block, I have decided to learn GitHub Desktop so that I can be sure I do not loose that much work again.  But this requires me to learn yet another system.
So I have made one edit to the Items.md file, and I have created a PR.  Hopefully I have done everything correctly, and this one change could be merged into the master docs.  But don't do the merge!  This is just a test to be sure if I put a lot of work into editing locally, that I have the workflow process right.  So for now, please drop a comment here to let me know things look okay (or not), and then I will go back and recreate my work.
Thank you for helping me to get up to speed on this.

**Comment by ThomDietrich** [comment]
Hey!

The change is based on the latest revision of the article and the Pull Request made it's way where we would need it to be. You've even correctly signed your commit. So far so good.

Let me add a few improvement ideas.

1. Add a commit message. Currently the Sign-off is the first line and hence became the commit message. [See](http://chris.beams.io/posts/git-commit/)

2. The big idea of git is to add changes (improvements) to something big gradually by the help of commits. So instead of typing for hours just to loose you work, git and also GitHub allow to create commits as "save points". Don't hesitate to create multiple commits. [See](https://github.com/openhab/openhab-docs/pull/494/commits)

3. You have created your commit in the main branch "gh-pages". That works but is unpractical. The main reason is, that the gh-pages branch is the one you've cloned from the main repository. If we both add changes to our individual copies of the gh-pages branch, that will create conflicts. Another reason is that one pull request is bound to one branch of your repository, hence you could only work on one pull request at any time. The recommended way to work on a pull request is in a dedicated branch. [See](https://guides.github.com/introduction/flow/)

4. As soon as you have opened a pull request, any subsequent commit to the PR branch will be part of the PR. You know that already. With that said, you could continue working on your items.md nit review in this PR/branch. Just change the PR title to something meaningful ;)

Getting started is never easy. GitHub Desktop is a good tool to help with that. I'd also suggest to check out some online resources about details like the ones I've mentioned. https://guides.github.com is quite good for that.

**Comment by bgilmer77** [comment]
Once again Thom, I really appreciate the feedback.  The only point that I need to research a little further is your comment about my making the commit in the main branch "gh-pages".  I will dig into this, but jumping ahead, the process should be Clone -> Branch -> Edit -> Commit -> PR.  Is that correct?  I will look at the references you provided tomorrow.

**Comment by bgilmer77** [comment]
@ThomDietrich thank you for your reply with the links to references.  This is extremely helpful.  I have read all of the information and am now seeking additional information on the forking process.  Once I think I have understood everything, I will try again.

**Pull request closed without merging**
