### PR TITLE
Replace all ".md" with ".html" inside zwave files on generation

### LINKED ISSUE #642: Broken links with ZWave documentation
Hey @ThomDietrich thanks for updating the docs with the latest version of ZWave readme, although it doesn't look to have copied over all the new thing files. This means that the link to the list of things is currently broken and docs.openhab goes 404 as a result.

When you get a chance could you take a look at this.

Thanks (and I hope the writing is otherwise going well ;) ).

### PR DESCRIPTION
**Pull request by BClark09**
Fixes #642 

I'm not sure if this is a "decent" way of doing it. But it does solve the issue of having links broken in either place.

CC: @cdjackson

@kaikreuzer, should I also add the new updated resources to this PR? Or will you run this later? I created a branch of this to see [here](https://github.com/openhab/openhab-docs/compare/gh-pages...BClark09:update-res)

Signed-off-by: Ben Clark <ben@benjyc.uk>

### CODE REVIEW

**Comment by BClark09** [comment]
Hmmm, apparently the -i parameter isn't the same as it is on Linux...

Might need some thought.

**Comment by kaikreuzer** [comment]
@BClark09 No need for any further thoughts, see https://github.com/openhab/org.openhab.binding.zwave/pull/912#issuecomment-391737433!

**Comment by BClark09** [comment]
Thanks! Shall we revert this PR?

**Comment by kaikreuzer** [comment]
Yeah, I guess so. Will do!

**Pull request merged**
