### PR TITLE
Remove `item=` parameter from Element Type Frame

### PR DESCRIPTION
**Pull request by AngelosF**
Closes: #306

Signed-off-by: Angelos agf@itcs.ro (github: AngelosF)

### CODE REVIEW

**Comment by watou** [comment]
Excellent -- this was a documentation mistake in openHAB 1.x that some widgets had `item=` documented but they didn't do anything and made no sense. 😄

**Comment by ThomDietrich** [comment]
I've actually tested all of these when rewriting the sitemaps article and "item" is indeed supported by the Frame element type.
However I saw the discussion in #306 and would also agree to remove it.

Thanks @AngelosF

**Comment by watou** [comment]
>  "item" is indeed supported by the Frame element type

While it may be supported syntactically, if it has no meaning and leads to confusion, it shouldn't be documented! 😄

**Comment by ThomDietrich** [comment]
> has no meaning

Well, that's your opinion.

2017-02-08 12_45_38-w66a openhab installation - pale moon

**Comment by watou** [comment]
> Well, that's your opinion.

I understood Kai's comment yesterday to be a definitive statement.  From https://github.com/openhab/openhab-docs/issues/306#issuecomment-277931667:

> I wasn't even aware that you can define a "normal" item for a frame. What does that do? How is that rendered? I am not sure that this actually makes much sense at all... The frames are really only meant to do some visual separation with a title, nothing more than that.

**Comment by ThomDietrich** [comment]
Ah I see.
I think the decision made here was "Either fix the brackets or remove the possibility". And as - as we seem to all agree - a value for a frame might seldom make sense, we just removed the documentation part for it.
Is an actual fix to remove or correct the presentation in the UI/API of interest? Maybe.

**Comment by Timtam** [comment]
Just to warm this up again, I just found this issue to be rather helpful to me. I'm currently building a forecast sitemap which shows the next 7 days weather forecast and thus each frame should have the date of the day in its label.
Because dynamic labels don't seem to be possible, I created a few items which get updated by a rather simple rule and now get used via Frame item=date_forecast_0d etc.
I don't find the brackets to be too disturbing, but I'd like to have the Frame element with its item parameter to be a feature rather than an undocumented hint somewhere within the forums.

**Comment by ThomDietrich** [comment]
Hey @Timtam I've since continued to use this as well. Would you like to drive this? Please create an issue here https://github.com/openhab/openhab-webui/issues for BasicUI to fix the brackets issue. Reference back to here and as soon as the issue got solved we can reintroduce the documentation part.

**Pull request merged**
