### PR TITLE
Add redirects for old OH2 binding links

### LINKED ISSUE #295: Links to add-on documentation in Paper UI are broken
Due to a change in the documentation structure (commit https://github.com/openhab/openhab-docs/commit/5be5bc2fb9d83777fc1116def6c5c5a45999a31c  @kaikreuzer ) it seems that all links to add-on docs are broken. The add-ons are using URLs like this:
```
http://docs.openhab.org/addons/bindings/allplay/readme.html
````
But the URLs have changed to:
```
http://docs.openhab.org/addons/bindings/oh2/allplay/readme.html
```
... and there seem to be no redirects.

BTW: The links in the search results are currently also wrong until Google has reindexed everything :-(.

### PR DESCRIPTION
**Pull request by watou**
Fixes #295.

Requires installation of [jekyll-redirect-from](https://github.com/jekyll/jekyll-redirect-from) plugin.

Signed-off-by: John Cocula <john@cocula.com>

### CODE REVIEW

**Comment by ThomDietrich** [comment]
> Requires installation of jekyll-redirect-from plugin.

Sadly not possible as we are on GitHub pages.
That's why I've build [this](https://raw.githubusercontent.com/openhab/openhab-docs/gh-pages/features/bindings.md). Yes I know, it's not quite as comfortable...

**Comment by watou** [comment]
OK, I see.  The readme for the plugin says to add it to the whitelist, but it doesn't say that the plugin isn't available on GitHub pages.  Oh well!

**Comment by watou** [comment]
...[this page](https://help.github.com/articles/redirects-on-github-pages/) says it's possible?

**Comment by kaikreuzer** [comment]
Is there any chance to keep the "old" links as the main/official links in place? If possible in any way, e.g. through the build process, this should imho be done. They are much more logical as they follow the same scheme that is used in distro extension service to identify add-ons.

**Comment by watou** [comment]
To have the add-on doc URLs track the feature names where "1" is appended to 1.x binding IDs, requires that the build process abandons the maven-resources-plugin for copying the source files.  Some Groovy code might have to do the job instead.

**Comment by watou** [comment]
Superseded by #297.

**Pull request closed without merging**
