### PR TITLE
[Sitemaps] Revise article, add element examples

### PR DESCRIPTION
**Pull request by ThomDietrich**
Includes all fixes for what was mentioned in https://github.com/openhab/openhab-docs/issues/53

I've also added the actual code used to create the sitemap elements in the screenshots for more clarity.

A typical section now looks like:

grafik

Signed-off-by: Thomas Dietrich <thomas.dietrich@tu-ilmenau.de> (github: ThomDietrich)

### CODE REVIEW

**Comment by bgilmer77** [comment]
@ThomDietrich, Thanks for asking me to take a look.  I believe the text below conveys the same information, and also answers some other questions implementers may have:

The 'Selection' element type renders a push-button menu where the user must select one, and only one choice.  Making a selection de-selects another choice that was previously selected.  [Question for @ThomDietrich - is this behavior correct?]  

When the user makes a menu selection, openHAB sets the value of the 'Selection item' to the value of the selected entry in the mapping.  In the example below, if the user chooses 'Cartoon Network', then LR_TV_Channel is set to the value '2'.  This is further described in the mappings section below.

When openHAB initializes, <itemname> is set to the value associated with the first mapping entry.  In the example below, the initial value would be set to zero.   [Question for @ThomDietrich, is this correct?]  Note that zero does not have to be the value associated with the first mapping entry; any legal value may be used.

**Comment by Confectrician** [comment]
I am still reading but wanted to add one comment already:
Maybe it is necessary to change some of the screenshots now, since they probably don't match the example.
This could be confusing for beginners.

**Comment by ThomDietrich** [comment]
@bgilmer77 you are referring to the screenshot but the Pull Request changes a lot more than that. See the "Files changed" tab on the top of this page: https://github.com/openhab/openhab-docs/pull/493/files

Thanks for your corrections, I'll add them to the PR.

@Confectrician Which do not match? At least one screenshot needs to be created for #492, so let's move that over there.
Let me know if you find any other problem!

**Comment by bgilmer77** [comment]
@ThomDietrich I understand your point.  But it is not clear to me where in openHAB the behavior of the Selection element type is established.  Two modes that are common are 'radio button' where you may choose one and only one selection from a list of choices (you do not have the option not to make a choice), and 'check box' where you may select zero or more choices from a list.  Where is this behavior determined?  
Also, when the system is initialized, is there a default state, or should we caution implementers that the system may come up in a random state so they should ensure that they use persistence, and that they set an initial power-up value for these parameters?

**Comment by ThomDietrich** [comment]
@bgilmer77 forgive me but I'm not sure what to extend.

Isn't it obvious that the selection offers the option to select *something*? The terms "radio button" and "check box" are known from other UI worlds, why are they important here? The selection is similar to a radio button but who would benefit from that analogy?

A multi-selection is not explicitly mentioned, which I feel would be mentioned if that was indeed possible - which it isn't.

Regarding the initialization of Items: That topic is unrelated to Sitemap elements. Of course that should be discussed somewhere and I think a chapter in the Items article would be the right place. How do you feel about that?

> should we caution implementers that the system may come up in a random state so they should ensure that they use persistence, and that they set an initial power-up value for these parameters?

In fact that's already covered partly: http://docs.openhab.org/configuration/rules-dsl.html#system-based-triggers

**Comment by ThomDietrich** [comment]
Please open a new issue if anything is still wort further discussion! ;) Thanks

**Pull request merged**
