### PR TITLE
Update frameworks and fix highlighting

### PR DESCRIPTION
**Pull request by ThomDietrich**
Related to #248 

This is the first step in improving the overall style of the page. More is coming soon.

* Update Materialize
* Replace deprecated material-design-icons by material-icons
* Replace all occurring icons
* Remove Highlight.js (never did a good job #248 , Jekyll 3.0 includes Rouge)
* Add Rouge jekyll style

To keep this PR as small as possible no content was changed, apart from the now working code syntax highlighting - which is also the most important improvement for now.

Next steps will go into the direction of a more Materialize framework based design, a cleanup of style.css and some rework of the main html structure. At this point we will deal with the mobile view and other known issues.

@Confectrician this might interest you.

Signed-off-by: Thomas Dietrich <thomas.dietrich@tu-ilmenau.de> (github: ThomDietrich)

### CODE REVIEW

**Comment by BClark09** [comment]
>> + fonts/roboto/Roboto-Regular.woff

Ah! There it is! 😆

**Comment by ThomDietrich** [comment]
Ah, you've watched the browser console I presume 😄

**Comment by Confectrician** [comment]
Sounds great and will give a good base for style restructuring.

**Comment by ThomDietrich** [comment]
Of course this broke everything. Please give me a few seconds :astonished:

**Comment by BClark09** [comment]
Hey @ThomDietrich, looks like this pull request broke the sidebar. :(

**Comment by ThomDietrich** [comment]
Thought so too, did you reload the page?
I hope this is not an issue for others as well...

**Comment by BClark09** [comment]
I did, and now it works fine :/ Not sure what that was about...

**Comment by ThomDietrich** [comment]
Happened to me on one out of two PCs. Most probably some cached resource. Let's hope this doesn't affect many.

If someone experiences the same issue, please investigate!

**Comment by Confectrician** [comment]
> Most probably some cached resource.
Agree.

No problems for me, while doing some browsing through the docs. :)

**Pull request merged**
