### PR TITLE
Add logo for ecowatt binding

### PR DESCRIPTION
**Pull request by lolodomo**
Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Review by stefan-hoehn — APPROVED** [review]
LGTM

**Comment by lolodomo** [comment]
Unfortunately, the logo is really top because on bright theme, the "watt" is not seen because white on white.

image

**Comment by stefan-hoehn** [comment]
Good catch, I will have an eye on that in the future. Will you provide an update?

What you could do is something like the following:

image

**Comment by lolodomo** [comment]
I took the icon from the official website.
One solution would be to replace white by a kind of grey.

**Comment by stefan-hoehn** [comment]
Or why not using this one?

image

**Comment by lolodomo** [comment]
Yes, looks better.

**Comment by lolodomo** [comment]
I am submitting a new PR...

**Pull request merged**
