### PR TITLE
Add webui repo to fix website build

### LINKED ISSUE #904: The UIs and classic iconset have disappeared from the final branch
As of https://github.com/openhab/openhab-docs/commit/f59c6dd5a62e5c99198409c6b72e8b585a9e7edd and Jenkins build https://ci.openhab.org/view/Documentation/job/gather-external-docs/170/

### PR DESCRIPTION
**Pull request by Confectrician**
Fixes #904

### CODE REVIEW

**Comment by Confectrician** [comment]
Build succeeds on my local machine.

Those errors and warnings are still there.
But they exist for ages and shouldn't stop the website build.
image
image

Maybe i can clean them up in the future, but i hadn't enough motivation yet.

**Comment by ghys** [comment]
Do you get the iconset and `_addons_iconsets` and all the UIs (habmin, habot,, habpanel, etc.) in `_addons_uis`?

**Comment by Confectrician** [comment]
image

Hm, i have to see, if the iconset was moved correct.
Rest should be fine.

**Comment by Confectrician** [comment]
Iconsets were indeed missing.

**Comment by Confectrician** [comment]
OK @ghys should be fine now and includes the iconset grabbed from the webui repo

**Pull request merged**
