### PR TITLE
first version for Eclipse IDE instructions

### PR DESCRIPTION
**Pull request by mvalla**
Signed-off-by: M Valla <mvbruincc@gmail.com>

See #955. I wrote a first version of the guide with Eclipse IDE. It works for me.
I also added a section to start writing a new binding using skeleton (which fails when adding the newly crated binding to features).
I did not find a better way to add the newly created binding to the demo.app other than recompiling openhab2-addons, probably there is a better way.

### CODE REVIEW

**Comment by Confectrician** [comment]
Hey @ghy, i am still a netlify rookie.
Can you give me a hint why the preview is failing here?
I would guess that the uploaded images are a problem for netlify preview.
Is that possible?

**Comment by Confectrician** [comment]
>Do not why it does not look as signed-off: I did all last commits with --signoff opt,

There's one commit missing, but this is no problem.
I can override the DCO Check, isnce there are signed off commits at all. 
image

About the build error:
I think this could be related due to the fact, that those images aren't existing in the repo yet.

**Comment by Confectrician** [comment]
Looks indeed like its just the pictures missing. (Which is fully ok since they are getting uploaded after this PR for the first time.)

image

**Comment by Confectrician** [comment]
@davidgraeff may i ask you to have a short look at the changed files?

I can find nothing that would prevent this pr from being merged.
I think the build issue will solve itself when the images are in the repo physically.

**Comment by davidgraeff** [comment]
The preview must succeed. Has the `https://github.com/openhab/openhab-docs/blob/master/.vuepress/process_main_docs.rb` file being changed to accomodate for the new pictures? I really don't like the current buildsystem in here tbh. Adding files should be enough.

I have read the changes already some days ago but didn't comment yet. The guide is now more detailed indeed, but at the same time Kai is working on making the setup file a valid option again. That might be easier for users. And we also don't use Markus demo repository anymore since like 2 days or so the demo app has been added to openhab-distro. So all in all it's a moving target.

We can of course merge this one, as it is an improvement. But we'll need to adapt sooner or later again.

**Comment by Confectrician** [comment]
>I really don't like the current buildsystem in here tbh. Adding files should be enough.

This is a problem for sure.
We can't expect new contributors to know this.
I haven't thought about this yet, until you pointed to it.

**Comment by Confectrician** [comment]
Here we go,

Thanks for the prepare script hint @davidgraeff.
https://5cd3424c7ff5e5000876fa3e--openhab-docs-preview.netlify.com/docs/developer/

Looks good from my side.

>We can of course merge this one, as it is an improvement. But we'll need to adapt sooner or later again.

This is a problem that will escort us every time.
Hopefully other IDEs will supplement the eclipse instructions in the future too.

**Comment by davidgraeff** [comment]
They will. I have worked on a Visual Studio Code workflow. That requires some ehm... changes that the OH2-addon guys need to be convinced of first.

**Comment by Confectrician** [comment]
Thanks for the effort @mvalla.

As you may see we have to improve out preview a bit.
Sorry for the delay caused to this.

>I have worked on a Visual Studio Code workflow.

I am already waiting for it. 🙂

**Comment by mvalla** [comment]
why the merged version is not yet online here: https://www.openhab.org/docs/developer/  ?
people out there are struggling to have an IDE working and this one guide at least seems to work

**Comment by Confectrician** [comment]
Please follow our issues.
The website build is broken currently and we are working on a solution.

**Pull request merged**
