### PR TITLE
[freeathomesystem] Apply logo for free@home binding

### PR DESCRIPTION
**Pull request by andrasU**
Apply logo for free@home binding

### CODE REVIEW

**Comment by florian-h05** [comment]
Hi @andrasU,

can you please provide the logo as SVG?
See https://next.openhab.org/docs/developer/addons/#add-your-add-on-s-logo-to-the-openhab-website-and-the-ui. 

@jlaur linked the stable docs deployed when openHAB 4.1.0 was released, I’ve added SVG support for add-on logos after the release so these docs there are outdated, the current ones are linked above.

**Comment by andrasU** [comment]
> Hi @andrasU,
> 
> can you please provide the logo as SVG? See https://next.openhab.org/docs/developer/addons/#add-your-add-on-s-logo-to-the-openhab-website-and-the-ui.
> 
> @jlaur linked the stable docs deployed when openHAB 4.1.0 was released, I’ve added SVG support for add-on logos after the release so these docs there are outdated, the current ones are linked above.

@florian-h05 
In the meantime I have the SVG version of the logo. I will push the change to this PR

**Comment by jlaur** [comment]
Please wait a bit merging this PR. The binding is currently in the process of being renamed from freeathomesystem to freeathome: openhab/openhab-addons#16718.

**Comment by jlaur** [comment]
@andrasU - can you rename the file to "freeathome.svg" now that the binding will be renamed?

**Comment by jlaur** [comment]
The binding has been renamed.

**Review by stefan-hoehn — APPROVED** [review]
@andrasU Can you try rebasing this because the other PRs run through.

**Pull request merged**
