### PR TITLE
Search input placeholder fix

### PR DESCRIPTION
**Pull request by kubawolanin**
Signed-off-by: Kuba Wolanin <hi@kubawolanin.com>

### CODE REVIEW

**Comment by ThomDietrich** [comment]
otg. Would you please post a screenshot!?

**Comment by kubawolanin** [comment]
Absolutely! :)
before:
before
after:
after

**Comment by MHerbst** [comment]
You were a bit faster than me with this change :-). Maybe one possible improvement: with this color the "search" placeholder looks like a normal menu entry. What do you think about writing it in italics?

**Comment by kubawolanin** [comment]
@MHerbst I think it's good like it is right now, We can tweak it a little bit in the future.

BTW. how do you feel about changing `#searchform .search-form-input:focus` not to set width, but rather increase padding, like this?
```css
#searchform .search-form-input:focus {
    padding-right: 30px !important;
}
```

This would give us a nice transition:
docs-search

**Comment by ThomDietrich** [comment]
I like the transition.
I do not like that "search" is at a different level as "GitHub".

**Comment by kubawolanin** [comment]
> I do not like that "search" is at a different level as "GitHub".
Once you've seen it, you cannot unseen it! ( ͡° ͜ʖ ͡°)
Let me fix that as well!

**Comment by MHerbst** [comment]
> @MHerbst I think it's good like it is right now, We can tweak it a little bit in the future.

OK. 

The padding looks really better. I like it.

> Once  you've seen it, you cannot unseen it! ( ͡° ͜ʖ ͡°)

:-) I had too look twice to see it but now its obvious.

Yesterday I have tried two more changes, maybe you can add them to your pull request:

For mobiles I have changed the color of the text entry. Maybe we should also make the placeholder a bit darker.
```
#querymob {
  color: #000;
}
```

When you use the Google input box on the search result page a border line appears at the bottom. We can get rid of it with this addition to the CSS:
```
input.gsc-input {
  box-shadow: none !important;
}
```

**Comment by ThomDietrich** [comment]
@kubawolanin should I wait or would you prefer this merged and @MHerbst creating a new PR?

**Comment by kubawolanin** [comment]
Let's go with this as it is now. I can submit new tweaks (not strictly related to searchbar) in a separate PR.
Thanks!

**Comment by ThomDietrich** [comment]
Okay I also prefer to have this merged now.

Btw pay attention to #248 

Thanks!

**Comment by ThomDietrich** [comment]
Hmmm this didn't work...

**Comment by MHerbst** [comment]
@kubawolanin I had a quick look. I think you have to add "!important" to the margin definition in line 27.

**Comment by ThomDietrich** [comment]
Hahaha. Without rating this solution in any way @MHerbst ;) I couldn't help but remember this tweet I once read: https://twitter.com/stefsull/status/422450802624458752

**Comment by MHerbst** [comment]
I now it's bad ..... :-) But sometimes it is the solution with the least impact on other style sheets.

**Comment by kubawolanin** [comment]
Oh that's a bummer. Sorry about that. 
I'm testing a hotfix now. It'll include @MHerbst's other changes proposed too!

**Comment by MHerbst** [comment]
There is another problem with the top margin. If you scroll the page down, the height of the menu is reduced. But this means the alignment of the search box is no longer correct. BTW: with the CSS the coloring of the placeholder does not work.

**Comment by kubawolanin** [comment]
Thank you @MHerbst! I've addressed that in #266

**Pull request merged**
