### PR TITLE
PIDController icon: Make lines thicker

### PR DESCRIPTION
**Pull request by jimtng**
Sorry to keep you busy @stefan-hoehn, I'm not good at this. Just got an idea to trace the bitmapped plot with bezier so I can make them thicker and more visible.

### CODE REVIEW

**Comment by stefan-hoehn** [comment]
> Sorry to keep you busy

No worries, it just keeps my away from checking your blockly PR 😝

IMHO, I liked the one with the thinner lines better ...

**Comment by jimtng** [comment]
I'll do a mockup to compare how they look shortly.

**Comment by stefan-hoehn** [comment]
convinced 👍 In comparison to the others the thicker line looks better.

**Review by stefan-hoehn — APPROVED** [review]

**Pull request merged**
