### PR TITLE
added innr and osram ledvance

### PR DESCRIPTION
**Pull request by PanderMusubi**
These systems are supported via hue bridge / zigbee. They don't have a specific binding, but are important systems to list, especially since the offer smart plugs, which Philips doens't offer.

Not sure how to add README.md files to openhab2-addons for systems without specific bindings. How does that work?

### CODE REVIEW

**Comment by Confectrician** [comment]
Maybe something for the hue docs article?
Or better the Zigbee one and add a link to hue.

Not sure about this either.

**Comment by PanderMusubi** [comment]
Yes, add to Zigbee documentation and link to it from hue documentation.

**Comment by Confectrician** [comment]
Hey @PanderMusubi,

May i jump in again?
Did you wanted to improve that yourself?

**Comment by PanderMusubi** [comment]
Yes, please jump in. I only added the logos.

**Comment by Confectrician** [comment]
I have to step back for now and would ask you to get active yourself.

**Comment by Confectrician** [comment]
I have opened #984 to adress this situation in general.

**Pull request closed without merging**
