### PR TITLE
Update logging.md

### PR DESCRIPTION
**Pull request by M-ax-G**
Added two more logging levels, which I have encountered when digging through log configs and source code. The two log level added are OFF and TRACE.

### CODE REVIEW

**Comment by ThomDietrich** [comment]
> [I hope this leads to the desired result.](https://community.openhab.org/t/help-im-ready-to-give-up/20006/66?u=thomdietrich)

Yes it did :+1:
The process with "Pull Requests" ensures, that every proposed change can reviewed by a second pair of eyes to increase docs quality. That's why I'll leave your PR open for a few hours, maybe someone else has a comment on that change.

Thank you!

**Comment by ThomDietrich** [comment]
I actually have one request already. The numbering is a bit off now. Could you simply itemize the list?
```text
* OFF
* ERROR
...
```

**Comment by M-ax-G** [comment]
Hmm, it shows 0. ... 5. for me... not stars... and 0 for OFF made sense, as the numbers increase (coincidently) with the level of logging (output).

**Comment by ThomDietrich** [comment]
Okay, that's a reasonable argument. The problem is, that markdown (the engine turning everything to pretty websites) will start numbering lists with 1. Have a look: https://github.com/M-ax-G/openhab-docs/blob/35ecfc36de769f8dd08a8ae0354d40ba0322a9d5/administration/logging.md#defining-what-to-log

So if you want to stay with numbering, that's okay with me but please start the list with "1."

**Comment by watou** [comment]
Should we document that logging can be set to `DEFAULT` to return it to its parent level?

```
log:set DEFAULT org.openhab.binding.foo
```

**Comment by ThomDietrich** [comment]
Definitely. Would you do that @M-ax-G ?

**Comment by M-ax-G** [comment]
@ThomDietrich : for this list to work, do I have to put a star before the item or the proper literal?

**Comment by ThomDietrich** [comment]
@M-ax-G Thanks again for your addition. I'm ready to merge it. Would you do one last thing, please sign your work as described here: https://github.com/openhab/openhab-docs/blob/gh-pages/CONTRIBUTING.md#sign-your-work

That means you need to add something like the following to your commits (or as an exception to the PR description above):

Signed-off-by: Thomas Dietrich <thomas.dietrich@tu-ilmenau.de> (github: ThomDietrich)

**Comment by M-ax-G** [comment]
@ThomDietrich : Happy to comply, but do not understand where to add this line to the commit... as these are only diff files... also, the PR above... these are all comments. So you see, what difficulties a new has with all of this. :) So; I will put the line in here, and next time try to add it as a comment to the PR or commit as a comment?!
Sort of sad that the e-mail address cannot be obscured; e.g. at a minimum with (at) for @.

Fixes #212  
Signed-off-by: Max Grenkowitz mxgrnkwtz@gmail.com (github: M-ax-G)

**Comment by ThomDietrich** [comment]
Hey @M-ax-G, these signing off rules have been a bit strange for me too at the beginning. However if you know about them, it's a rather small detail to pay attention too.
These rules are quite important for the development parts of openHAB, where intellectual property violations, especially in the binding development area, could become a real problem for openHAB as an open source platform. See [here](https://github.com/openhab/openhab-docs/pull/213#issuecomment-273298283)
Hope to see more from you soon! ;)

**Pull request merged**
