### PR TITLE
[interpret action] document use multiple interpreters

### PR DESCRIPTION
**Pull request by GiviMAD**
Document changes in https://github.com/openhab/openhab-core/pull/2906.
@J-N-K 
Signed-off-by: Miguel Álvarez Díez <miguelwork92@gmail.com>

### CODE REVIEW

**Comment by Confectrician** [comment]
Does this need the linked PR to be merged before getting it in the docs?

**Comment by J-N-K** [comment]
Yes.

**Comment by GiviMAD** [comment]
https://github.com/openhab/openhab-core/pull/2906 is merged

**Comment by lolodomo** [comment]
@GiviMAD : I did not see your PR and created PR #1816 which contains more things. Are you ok to close your PR in favour of mine ?

**Comment by GiviMAD** [comment]
| I did not see your PR and created PR https://github.com/openhab/openhab-docs/pull/1816 which contains more things. Are you ok to close your PR in favour of mine ?

@lolodomo, sure!

**Comment by lolodomo** [comment]
And your information, I will create another PR to add a section "Dialog processing" to cover startDialog/stopDialog and listenAndAnswer features.

**Comment by Confectrician** [comment]
Thanks for keeping an eye on the open Prs. :)

**Pull request closed without merging**
