### PR TITLE
Enhance DSL rules for say and interpret

### PR DESCRIPTION
**Pull request by lolodomo**
Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
Please wait for the merge of https://github.com/eclipse/smarthome/pull/2593

**Comment by ThomDietrich** [comment]
NIce addition ;) Regarding the example: now there is a mixture of mactts and voicerss...

**Comment by lolodomo** [comment]
I enhanced again the documentation.
All this is now available in recent snapshots.
So the PR is ready for a merge.

**Comment by ThomDietrich** [comment]
Thank you @lolodomo. LGTM but would still like to encourage you to use one voice service for the example (mactts vs. voicerss).
I'd like to wait with this PR till #148 is merged.

**Comment by ThomDietrich** [comment]
I've moved the file you are doing changes to with #148 please update your PR. Thanks

**Pull request closed without merging**
