### PR TITLE
Update designer.md regarding snapshot bug

### PR DESCRIPTION
**Pull request by ThomDietrich**
Signed-off-by: Thomas Dietrich <thomas.dietrich@tu-ilmenau.de> (github: ThomDietrich)

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Did you test the recent snapshot? It might actually be finally usable since around 2 weeks (have to check myself though...)

**Comment by ThomDietrich** [comment]
Not today. I believe to have tested it after https://github.com/eclipse/smarthome/pull/2891 and it didn't work yet. I've created this PR after I was triggered in this thread, making me believe it's still not settled: https://community.openhab.org/t/eclipse-designer-unable-to-see-any-paperui-created-things-items/22203/3

Let's put this PR on hold, I'll test this evening (if time).

**Comment by ThomDietrich** [comment]
@kaikreuzer Indeed items and rules are now working again.
However the situation didn't get better. I'll post my findings in the other thread.

I would merge this PR. Using the stable release is not a bad advice in the official documentation and instead of recommending the snapshot, the version 0.9 should be released as stable as soon as the issues are sorted out.

Would you agree?

**Comment by kaikreuzer** [comment]
Yes, sir!

**Pull request merged**
