### PR TITLE
Fix errors in synology.md

### PR DESCRIPTION
**Pull request by lolodomo**
Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
@stefan-hoehn : please merge this one to unlink all others.

**Review by stefan-hoehn — APPROVED** [review]
Thanks, very much appreciated. I was just about to do that myself. I will then run all dependant other PRs as well. LGTM.

**Comment by lolodomo** [comment]
I am going to update all my other PRs now to get successful builds.

**Comment by stefan-hoehn** [comment]
Why do you need to update your PR? I rerun #2154 and it still failed.

**Comment by lolodomo** [comment]
> Why do you need to update your PR? I

To have updated synology.md in my branch.

This is done.
You can now expect all my PRs building with success.

**Comment by lolodomo** [comment]
Apparently, it remains a problem at line 90 in synology.md !!!

**Comment by stefan-hoehn** [comment]
My bad: I just noticed that I didn't look closely enough on synology.md as we overlooked one part:

image

**Comment by lolodomo** [comment]
Error: installation/synology.md:98:1 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 3]

Can you please fix it ?
I will take a break now.

**Comment by stefan-hoehn** [comment]
Also having a break now but I will take care asap!

**Pull request merged**
