### PR TITLE
Clarify cloud notification action documentation

### PR DESCRIPTION
**Pull request by maniac103**
Add more concise parameter description, and document the action variants that accept an icon and a severity level.

### CODE REVIEW

**Comment by maniac103** [comment]
See discussion at https://github.com/openhab/openhab-docs/issues/479#issuecomment-403596395

**Comment by Confectrician** [comment]
Hi @maniac103 and thanks for taking care of the actions finally.

I have to request one thing:
You would have to `sign-off` your change according to our [contribution guidelines](https://github.com/openhab/openhab-docs/blob/gh-pages/CONTRIBUTING.md#sign-your-work).

For first time contributions in the docs its ok to edit the Pull Request description and add a line like this one (of course with your data):

> Signed-off-by: Joe Smith <joe.smith@email.com> (github: github_handle)

After that we are fine to merge your changes into the docs.

**Comment by maniac103** [comment]
> Very good PR. Thank you. Could you please add information on where to find the allowed severity levels?

The severity field is (to my knowledge) free-form text. When https://github.com/openhab/openhab-cloud/pull/175 is merged, the Android app will use it 
- to show it in the notification list and
- as notification category, so you can have different notification behavior for each severity level

Both items do not rely on specific values there. AFAIK the iOS app doesn't use severity and icon at all yet.

> You would have to sign-off your change according to our contribution guidelines.

Sure, will do.

**Comment by Confectrician** [comment]
>Thinking about it, I wonder whether I should add the above piece of information to the docs?

We can add a dependency label and wait for it to be merged first befor merging this pull request.

**Comment by Confectrician** [comment]
Hey @maniac103 i think we can merge this one now since the dependency pr has been merged.
Do you agree?

**Comment by maniac103** [comment]
@Confectrician Yes, I agree, this one should be good to go.

**Pull request merged**
