### PR TITLE
explain lowercase filenames for icons in migration tutorial

### PR DESCRIPTION
**Pull request by macmeck**
Pointing out that icons in conf/icons/classic need to be lowercase only. 
Also updated spelling in the icon section of configuration/items

### CODE REVIEW

**Comment by ThomDietrich** [comment]
Hey @macmeck, thanks! There is already a bigger PR editing the items file open. Could you comment there instead please! Thanks
https://github.com/openhab/openhab-docs/pull/250/files

**Comment by macmeck** [comment]
@ThomDietrich okay, I reverted the changes from the item documentation and commented PR #250

**Comment by ThomDietrich** [comment]
@macmeck Thank you. Sorry for getting back to you only this late. I'm not sure if the sentence you want to add here is meaningful. As we know from the items article, a lot more requirements are true for icons. We should either name all of them or (my preferred choice) link the items.html -> Items article. What do you think?

**Comment by macmeck** [comment]
@ThomDietrich, during the migration, the "only lowercase filenames are accepted" hit me several times (I must have forgotten about it in the meantime). This seems to be a change since 1.x, the error messages are not very helpful and there have been several questions concerning migrated icons in the community. So I think this is worth mentioning here for the migration path.
An additional link to the items page might indeed be a good idea. I'll try to add it to the PR during the next couple of days.

**Comment by macmeck** [comment]
@ThomDietrich I just updated the PR... does that make it clearer now?

**Comment by ThomDietrich** [comment]
Hey @macmeck, yes I like it. The only thing throwing me off is the last sentence. It's not related to icons and Classic UI is not a sitemap but just the old sitemap presentation from OH1. The relation between Classic UI and Basic UI is discussed elsewhere. Sorry for the back and forth. To not make this PR take any longer, I'll remove the sentence and merge afterwards. I hope that's okay with you.

Thanks for your contribution!! ;)

**Pull request merged**
