### PR TITLE
Changed Linux Installation to Refer to Bintray

### PR DESCRIPTION
**Pull request by BClark09**
Signed-off-by: Ben Clark <ben@benjyc.uk>

### CODE REVIEW

**Comment by ThomDietrich** [comment]
Hey Ben, looks good to me. There is one more part you might want to change:
grafik

Is the change I just committed correct?

**Comment by BClark09** [comment]
Thanks @ThomDietrich, I think I missed that line. In reality the sentence either way is a little misleading. It's more appropriately a nightly build with the latest incoming contributions as the CI server triggers the Debian build after it's finished building the archive. What I think it's trying to say is that the Debian builds are made on each change of the "openhab-distro" builds as seen in the original link.

**Comment by ThomDietrich** [comment]
didn't quite get that but just change the sentence however you see fit ;)

**Comment by ThomDietrich** [comment]
@BClark09 satisfied? ;)

**Comment by BClark09** [comment]
Thanks @ThomDietrich! That's perfect! I've just added the addons path as I noticed it was missing and will be important in the next package changes.

**Comment by ThomDietrich** [comment]
Thanks @BClark09, that's a great idea.

**Pull request merged**
