### PR TITLE
Remove automatically generated concepts articles.

### PR DESCRIPTION
**Pull request by Confectrician**
Seems the base branch change broke my fork completely.
Or it was my existing experimental master branch...

Anyway no time to look at this now, so a pr branch directly from the repo.

Signed-off-by: Jerome Luckenbach <github@luckenba.ch>

### CODE REVIEW

**Comment by ghys** [comment]
The merge job fails because it's not a clean merge; it was to be expected. I'll fix it manually, without PRs (sorry).

**Comment by Confectrician** [comment]
But now it succeeded. 🙂

**Comment by ghys** [comment]
Yeah I had to resolve the conflict by hand, it was a special situation. From now on conflicts shouldn't happen anymore: either the content is local and never committed to final without going through master first, or it's external and it doesn't appear in master. 😄

**Comment by Confectrician** [comment]
I think there will be some problems left with existing github forks and those PRs.
I had to delete the local folder completely and clone the fork again.
But now i have the master branch up to date and changed it to default.

**Comment by ghys** [comment]
For PRs you can use the Edit button near the title and change the base branch. I admit I never tried it.

**Comment by Confectrician** [comment]
You can -> already done for all of my open prs about an hour ago.
But the recommend way should be to update the fork, thats what i wanted to say. :)

So we have to explain this for a bunch of PRs in the next time.

**Pull request merged**
