### PR TITLE
Fix the command to access the console

### PR DESCRIPTION
**Pull request by lolodomo**
and add an advice in case the command fails.

### CODE REVIEW

**Comment by lolodomo** [comment]
Will fix #91

**Comment by ThomDietrich** [comment]
Thanks for the fix! I do however not feel comfortable with the "advice". This file is quite important in the security concept of an ssh installation and users should not be invited to blindly delete it.
What is the problem you are trying to solve by that step?

**Comment by lolodomo** [comment]
https://community.openhab.org/t/ssh-session-timing-out-on-slow-hardware/14008
Something was changed in the security setup and I think my SSH connection with the old OH setup was saved in known.hosts, preventing a new connection with new OH security setup.

**Comment by ThomDietrich** [comment]
In this case you should have seen a warning, telling you to delete one line from that file, just as Red_Wraith suggested. Deleting only one specific line when prompted to do so is okay. Did you get that warning? In this case I don't think a mentioning in docs is needed.

**Comment by maggu2810** [comment]
You can delete the old entry in the known hosts file using "ssh-keygen -R ..." or you can use command line parameters for "ssh" to "ignore" the known hosts file for this connection.

**Comment by ThomDietrich** [comment]
Hey @lolodomo, I've tuned your contribution a bit. Are you okay with them?

**Comment by lolodomo** [comment]
No problem

**Comment by ThomDietrich** [comment]
Merged. Thank you!

**Pull request merged**
