### PR TITLE
update docs for core.GenericEventTrigger

### PR DESCRIPTION
**Pull request by ccutrer**
see https://github.com/openhab/openhab-core/pull/3299

### CODE REVIEW

**Comment by stefan-hoehn** [comment]
@ccutrer Do you intend to eventually finish the doc as the related PR has been closed already?

**Comment by ccutrer** [comment]
Thanks for the reminder. I'll fix the conflict and have it ready for review today or tomorrow.

**Comment by rkoshak** [comment]
This is a minor thing, but is there a place we can look to see what "etc" all covers? What is the full list of events that GenericEventTrigger can handle? I'm assuming the missing ones are InboxUpdatedEvent, RuleStatusInfoEvent, RuleAddedEvent, RuleRemovedEvent, StartlevelEvent, and AddonEvent but that's just based on mucking around in log4j2.xml, though looking at the [Event interface](https://www.openhab.org/javadoc/latest/org/openhab/core/events/event), maybe there are a lot more. Are these *all* supported by GenericEventTrigger?

It'd be great if we could replace "etc." with a link to the full list. Even if it's just to that JavaDocs page.

**Comment by ccutrer** [comment]
AFAIK there's not a full list. The Javadoc is probably the closest, because it's finding all subclasses of Event. But in practice any addon or even JSR script could define additional types. I'd be happy to link to the javadoc though.

**Comment by rkoshak** [comment]
Linking to the JavaDoc and mentioning that add-ons can create their own (something I didn't know) would be much better than "etc." in my book.

**Comment by ccutrer** [comment]
It looks like the Digiplex binding is the only one that does (in openhab-addons), but it has 6 of them!

**Comment by stefan-hoehn** [comment]
@rkoshak Are you fine with @ccutrer 's comment?
@ccutrer Is the PR ready to be merged?

**Comment by ccutrer** [comment]
Pending @rkoshak's approval of how I worded it, yes.

**Comment by rkoshak** [comment]
Sorry, I didn't realize I was the hold up. It looks good to me!

**Review by stefan-hoehn — APPROVED** [review]
LGTM

**Pull request merged**
