### PR TITLE
Apitokens documents created

### PR DESCRIPTION
**Pull request by lampy2**
Created doc for creating API tokens in OH3.

Signed-off-by: Gerwin Lammers <gerwinlammers@gmail.com>

### CODE REVIEW

**Comment by Confectrician** [comment]
Thanks in advance @lampy2 🙂 

I have already seen some small things.
But maybe i can help you first. 

What's the reason for pushing that many commits?
Maybe you can tell what you want to achieve. 🙂

**Comment by lampy2** [comment]
Hi @Confectrician, yes I do believe it it not all going according plan. 
Actually I tried to follow the last step _Make a pull request from yourFork/openhab-docs apitokens-edit branch to openhab/openhab-docs main branch_.
Updated the Commit text of screenshots in my own fork, then went to the github website to create the pull request (together with the signoff as described on the forum). 
But now the bot tells me the DCO has failed :s

**Comment by Confectrician** [comment]
Did you press the synchronize button in vscode after opening the pull request?
It seems that you have synced open changes from vscode to your fork after opening the pull request.

Those will then be regocnised here as new changes.

**Comment by lampy2** [comment]
Hmm this might be case indeed. Tried to follow the link to the update the DCO in the commits, but in my attempt to get the _git rebase HEAD~21 --signoff_ working I might have hit that sync button.

**Comment by Confectrician** [comment]
You can try to do the dco check part again.

It is splitted in two commands.

- Rebase command
- force push command

this should do the signoff trick and it should merge those 21 commits into one.

**Comment by lampy2** [comment]
Hmm I don't get this working now. Perhaps the best if I close this and start over. I can keep the files so should not be to much of an issue?

**Pull request closed without merging**
