### PR TITLE
[Eclipse IDE setup] Update IDE picture for installation

### PR DESCRIPTION
**Pull request by Jochen1980**
see #902

### CODE REVIEW

**Comment by davidgraeff** [comment]
The changes list is empty?

**Comment by Jochen1980** [comment]
Dear David, 

I just changed the picture - the file name is the same, so I guess it looks like 'no changes'.

Best regards,
Jochen

**Comment by davidgraeff** [comment]
Sweet. It would be even more helpful if you focus the list view onto the extended Github projects->openHAB selection, don't you agree?

**Comment by Jochen1980** [comment]
Actually I do not think so in that picture. The extended Github-projects view will show up after hitting "Next". In my opinion it would be more appropriate to add another picture if you want to focus on that matter.

Just my two cents ...

**Pull request merged**
