### PR TITLE
Replace and fix invalid links

### LINKED ISSUE #117: 404 Page Breaks after third 'depth'
My latest change works up until the third sub-directory for example: http://docs.openhab.org/one/two/three

It looks like the header and footer isn't applying base.html as intended and I'm not entirely sure of the reasoning behind the process. Why is {{base}} used all over in the first place? Surely a working  `<script src="{{base}}/js/jquery.min.js"></script>` is the same as `<script src="/js/jquery.min.js"></script>` etc. which sets the initial level? 

What is the necessity to calculate {{base}} by breaking down the target url?
##

### PR DESCRIPTION
**Pull request by BClark09**
Fixes #117 (and the change here is discussed in the comments) and addresses all of the current broken links to openHAB pages at the time of the PR.

Signed-off-by: Ben Clark <ben@benjyc.uk>

### CODE REVIEW

**Comment by ThomDietrich** [comment]
Great contribution as always ;) Thanks

**Comment by ThomDietrich** [comment]
How did you check for invalid links? I used this page https://github.com/openhab/openhab-docs/issues/103 the last time. If you've got a bash script ready to do the job: Care to share?

**Comment by BClark09** [comment]
I had a difficult time trying to make a bash script to test broken links within the sites are because of how some of them are autogenerated.

I used linkchecker (which should be available for most debian packages) to help me.

```
sudo apt-get install linkchecker
linkchecker -F text/invalidlinks.txt --check-html --check-css --check-extern --ignore-url=^.*/font/ http://localhost:4000/
```

**Comment by ThomDietrich** [comment]
Good enough :+1: Can you add this to the issue?

**Pull request merged**
