### PR TITLE
Refactor concepts/categories.md page.

### LINKED ISSUE #1061: What has happened to the Concepts / Categories page?
We have nearly five links to it (https://www.openhab.org/docs/concepts/categories.html) in the [Binding Definitions](https://www.openhab.org/docs/developer/bindings/thing-xml.html#channel-categories) section and maybe much more in other places. But we only get a 404 when navigating to the link.

Why did we exclude it during creation? Any specific reason? What can be done to include it again?

https://github.com/openhab/openhab-docs/blob/87a37fba0d05575f4c1c79c5f5a3be2f4b4e11a7/.vuepress/process_main_docs.rb#L25-L30

### PR DESCRIPTION
**Pull request by Confectrician**
Fixes #1061 

I have just replaced the loops with some old content.
When this is fine, we can publish it for now and do a refactoring and move to the development area afterwards.

cc @cweitkamp @martinvw @ghys 

Please have a look. Since i did a 1 to 1 refactoring for now, there may be some icon issues.

Signed-off-by: Jerome Luckenbach <github@luckenba.ch>

### CODE REVIEW

**Comment by martinvw** [comment]
Great.

However I'm a litte bit confused about the relation between the page @cweitkamp mentioned:

https://deploy-preview-1103--openhab-docs-preview.netlify.com/docs/developer/bindings/thing-xml.html

And the page in which I end up through the menu

https://deploy-preview-1103--openhab-docs-preview.netlify.com/docs/developer/bindings/#handling-thing-bridge-removal

Is there even a route to the page mentioned in the original issue?

**Comment by Confectrician** [comment]
>And the page in which I end up through the menu

Which menu entry are you talking about?
I can't see where you tried to access it, so i cant't check possible routes now.

**Comment by cweitkamp** [comment]
Looks good so far. Preview did not show icons for me.

@martinvw You can access the page I am referring to from the page you can find in the menu (Developer Guide -> Bindings). There are cross links in the first section (Structure of a Binding -> binding XML reference) and second section (Describing Things -> Thing & Channel XML reference).

**Comment by Confectrician** [comment]
>Preview did not show icons for me.

Yes. Icons are not part odf the preview, as i recognised too at that time.
We have to check them afterwards in the live system.
If there are broken ones i will push a fix without PR then.

**Comment by martinvw** [comment]
> @martinvw You can access the page I am referring to from the page you can find in the menu (Developer Guide -> Bindings). There are cross links in the first section (Structure of a Binding -> binding XML reference) and second section (Describing Things -> Thing & Channel XML reference).

Found it thanks! LGTM

**Comment by Confectrician** [comment]
Thanks for the feedback.
Let's see which icons will be broken. then.

**Comment by Confectrician** [comment]
Dependency PR: https://github.com/openhab/website/pull/220

**Pull request merged**
