### PR TITLE
Add and update add-on icons

### PR DESCRIPTION
**Pull request by mherwege**
This PR adds or improves a number of add-on icons.

It includes icons for all add-ons from A-N.

### CODE REVIEW

**Review by stefan-hoehn — CHANGES_REQUESTED** [review]
https://www.openhab.org/docs/developer/addons/#add-your-add-on-s-logo-to-the-openhab-website
These are the requirements for logos:

PNG (transparency is preferred)
512x512 pixels or smaller in one dimension, if it's not a square logo
Less than 30kB

The following are bigger in size that 30KB

images/addons/ftpupload.png
images/addons/jeelink.png
images/addons/mcp23017.png
images/addons/mecmeter.png
images/addons/meteoalerte.png
images/addons/meteostick.png
images/addons/milight.png
images/addons/mpd.png

**Comment by stefan-hoehn** [comment]
The following image is too big:
images/addons/folderwatcher.png

Not sure if we want to make sure all have a transparent background...

**Comment by stefan-hoehn** [comment]
@mherwege Do you want me to do a PR on your repo to fix these issues or is there an easier way to support you?

**Comment by mherwege** [comment]
@stefan-hoehn I didn’t get to this again yet. I intended to go through all add-ons and get icons for as many as I can. But feel free to create PR’s against my PR. I will accept them to move things forward.

**Comment by stefan-hoehn** [comment]
@mherwege Sorry, it took so long. Thanks for originally starting it!

Finally I had the time to work on the images and reduce quite a number of them. Even though it is really hard to reach the intended 30KB limit what helps is reduce the image size and save it as 8Bit PNG (I at least see no difference after the conversion).
So we should be good now. Would you mind having a quick check of the ones I provided to double check it. I would then merge it finally...

**Review by stefan-hoehn — APPROVED** [review]

**Comment by mherwege** [comment]
@stefan-hoehn Thanks for merging, and sorry I didn't check anymore. When I have time, I will see what I can do for the rest of the alphabet not covered by this PR yet.

**Comment by stefan-hoehn** [comment]
You'll find that in the website-repo in AddonSearch.vue:

Most likely this is the line you are looking for: 
https://github.com/openhab/website/blob/b445fc1e49262713092d3a8d2e088c6cd7767fd4/.vuepress/components/AddonSearch.vue#L31

**Pull request merged**
