### PR TITLE
readability improvements

### PR DESCRIPTION
**Pull request by mstormi**
Signed-off-by: Markus Storm <markus.storm@gmx.net>

### CODE REVIEW

**Comment by ghys** [comment]
Thanks!
We don't accept PRs against the `2.5.x` branch anymore, can you please rebase your changes to the `main` branch?

**Comment by mstormi** [comment]
uhm, ok. But this is what happens if you click the 'edit' at the bottom of a docs page so you should probably change that, too ?

**Comment by ghys** [comment]
touché - this should be taken care of asap...

**Comment by ghys** [comment]
https://github.com/openhab/website/pull/250 (will be merged soon) ensures that clicking on "edit" links on the website will offer opening PRs to the main branch.

**Comment by mstormi** [comment]
I opened #1278 against main instead

**Pull request closed without merging**
