### PR TITLE
Initial addition of jsondb overview

### PR DESCRIPTION
**Pull request by cdjackson**
Signed-off-by: Chris Jackson <chris@cd-jackson.com>

### CODE REVIEW

**Comment by AngelosF** [comment]
This is much better :)

**Comment by cdjackson** [comment]
Sorry - much better than what??? The placeholder?

**Comment by AngelosF** [comment]
Than this: https://github.com/openhab/openhab-docs/pull/281

I didn't see your PR, so I made an effort to type up something for the JsonDB

**Comment by cdjackson** [comment]
Ah - sorry - I didn’t see that :). Maybe a combination is about right - mine was a quick writeup during lunchtime…

**Comment by ThomDietrich** [comment]
Hey @cdjackson,
thank you! It will be great to have some documentation on the jsondb, users might need to know about more at times. Regarding the conflict with @AngelosF, I would suggest to merge yours first and he can merge his content in the next step. (as suggested in https://github.com/openhab/openhab-docs/issues/202) Would you agree?

One change request: Could you please break down your paragraphs to one line per sentence? Thanks!

**Comment by cdjackson** [comment]
> users might need to know about more at times.
Ok - what more do you want me to add though?


> Regarding the conflict with @AngelosF <https://github.com/AngelosF>, I would suggest to merge yours first and he can merge his content in the next step. (as suggested in #202 <https://github.com/openhab/openhab-docs/issues/202>) Would you agree?
Yes - that’s fine. I would just suggest to be a bit careful about trying to explain the actual format of these files since there will be many of them, and they will evolve as the framework evolves. This is why I elected not to try and describe the content - up to you though.

**Comment by ThomDietrich** [comment]
>> users might need to know about more at times.
>
> Ok - what more do you want me to add though?

Nothing, this was directed at your text, as in "more than nothing right now" :)

**Comment by ThomDietrich** [comment]
@cdjackson I just wanted to merge this, sadly you still need to sign your contribution (squash commit message or simply in the initial posting) Thanks

**Comment by cdjackson** [comment]
Sorry - did this during lunch at work so didn't use my standard tools ;)

**Comment by ThomDietrich** [comment]
No problem. Thank you!

@AngelosF ping ;)

**Pull request merged**
