### PR TITLE
[metOfficeDataHub] logo addition

### PR DESCRIPTION
**Pull request by dag81**
Addition of logo for new metofficedatahub binding, this is for the representation of this binding covered in this PR: https://github.com/openhab/openhab-addons/pull/15367

### CODE REVIEW

**Comment by dag81** [comment]
Changing to non-draft - so its ready after the binding is merged.

**Review by stefan-hoehn — COMMENTED** [review]
Can you remove a bit of the margin around the logo?

**Review by stefan-hoehn — APPROVED** [review]
Thanks, Looks good to me.

**Comment by dag81** [comment]
@stefan-hoehn Thank you for the quick merge :)

**Pull request merged**
