### PR TITLE
Fix Typo

### PR DESCRIPTION
**Pull request by Trysupe**
Signed-off-by: Felix Schneider <fs@felix-schneider.org>

### CODE REVIEW

**Review by Confectrician — COMMENTED** [review]
`reasons lies` sound wrong to mee too. 🤔

**Comment by Trysupe** [comment]
> `reasons lies` sound wrong to mee too. 🤔

It's a common phrase: https://www.linguee.de/englisch-deutsch/uebersetzung/the+reason+lies+within.html

**Comment by Confectrician** [comment]
Yeah i know that phrase but the current text ist `reasonS` `lies` i think you forgot to delete the `s` behind `reason` then.
Since its now clear what was meant just remove that and we can merge. :)

**Comment by Trysupe** [comment]
2 be honest: I read `reason` and not `reasons`. Of course `reasons lie` is correct

**Comment by Confectrician** [comment]
I am fine with both versions, so leave as is it will be for now.
Thanks anyway for staying active here. :)

**Pull request closed without merging**
