### PR TITLE
Update model.md

### PR DESCRIPTION
**Pull request by clinophobic**
First time ever trying to do this trying to update the advanced model image as without it's hard to see the no semantic groups

### CODE REVIEW

**Comment by Confectrician** [comment]
Hi @clinophobic and thanks for your contribution.

I would suggest to better upload the picture instead of just linking to an external source.
I would expect that you have choosen this image from our community forum.

If you may point me to the specific posting, i will help you uploading the picture here and replace the current one.

**Comment by clinophobic** [comment]
> Hi @clinophobic and thanks for your contribution.
> 
> I would suggest to better upload the picture instead of just linking to an external source.
> I would expect that you have choosen this image from our community forum.
> 
> If you may point me to the specific posting, i will help you uploading the picture here and replace the current one.
Apologies I will read up on how to upload images. 

I got the image from the following post https://community.openhab.org/t/oh3-meaning-of-locations-and-groups/111171/2

**Comment by Confectrician** [comment]
Thanks for the hint @clinophobic 

I have downloaded the original picture and replaced the old one by keeping the name.
So we are able to keep track of this completely on our own. 🙂

**Review by Confectrician — APPROVED** [review]
Perfect. Thanks for taking the step here to contribute this. 👍

**Comment by clinophobic** [comment]
Thanks now that i found its not as daunting as I first thought I will try help put more effort with docs. Thanks for all the work you all do

**Pull request merged**
