### PR TITLE
Corrected link to ESH.xml

### PR DESCRIPTION
**Pull request by openhab-5iver**
Signed-off-by: Scott Rushworth openhab@5iver.com

### CODE REVIEW

**Comment by openhab-5iver** [comment]
I think the signoff needs a blank line above it, but I'm not going to take the time to amend the commit (sorry!).

**Comment by Confectrician** [comment]
>I think the signoff needs a blank line above it

I think you have forgotten the `<>` brackets, which lets dco fail.
But no need to amend anything. I will override the check and correct this.

**Comment by Confectrician** [comment]
Copy of #972

**Comment by Confectrician** [comment]
And it doesn't work like #972 also doesn't work.

@ghys can you have a look?
Is it possible that `xml` files don't get processed?

I think i had already a look into the settings and faced this as reason.
But i am not sure if we should change the script or better put a full url link to the raw version on github.

**Comment by Confectrician** [comment]
I have added a temporary solution through #972 and created #992 to get a stable one on long term.

**Pull request closed without merging**
