### PR TITLE
[Docker] Update docker image tag

### PR DESCRIPTION
**Pull request by cniweb**
Signed-off-by: Christian Häussler <c-n-i@web.de> (github: @cniweb)

### CODE REVIEW

**Comment by ThomDietrich** [comment]
Thanks!

Btw. Christian. For many other topics in documentation, whose article is related to another repository, we went with the new approach to have the documentation article in the respective repository and then duplicated on a regular basis. That would most probably be a nice step for you, correct?

See #516 to see how I did that with openHABian.

If you are interested:
Please provide the file [docker.md](https://github.com/openhab/openhab-docs/blob/gh-pages/installation/docker.md) at https://github.com/openhab/openhab-docker/blob/master/USAGE.md or https://github.com/openhab/openhab-docker/blob/master/docs/USAGE.md

**Comment by cniweb** [comment]
Hello @ThomDietrich, yes that would be a good step. Is it sufficient if I create a docs folder and create a USAGE.md file with the appropriate content?

**Comment by ThomDietrich** [comment]
Yes that would be it. If you want to include images, please add them in the subfolder "docs/images". If you don't think that will be needed, you can place the USAGE.md in the root of the repository. I'm pretty flexible in that regard as all that is needed in the end is: https://github.com/openhab/openhab-docs/blob/gh-pages/pom.xml#L412-L422

**Comment by cniweb** [comment]
Ok, I understood. Could you merge this PR please. I would then rebuild the two documentation in the next days. Thank you.

**Pull request merged**
