### PR TITLE
Resolve merge conflicts / Fix CI builds

### PR DESCRIPTION
**Pull request by Confectrician**
@ghys may you have a short look?

This should sync the branches again and resolve the existing merge conflicts.

### CODE REVIEW

**Comment by ghys** [comment]
@Confectrician I suppose?
What caused the conflicts?
When merging I think you should rebase & merge in this case.

**Comment by Confectrician** [comment]
> What caused the conflicts?

I have removed paper ui, openhabian and habpanel pages.

First one is deprecated for oh3 and had only been removed from the sidebar so far.
Both of the other pages are being maintained in their code repos for a longer time.
Seems that this caused some conflicts, since the pages are getting gathered from ci too.

We have to do a manual merge for the gathering part too probably.

**Comment by Confectrician** [comment]
> When merging I think you should rebase & merge in this case.

Rebase and merge is not possible in this case 
image

Since we have the history available in the main branch, squash should be suitable to.
Wdyt?

**Comment by ghys** [comment]
I think the last time I made it with the git command line. If you want I can try again.

**Review by ghys — APPROVED** [review]
Ah, you know what, let's squash, the history's on main anyway as you said.

**Pull request merged**
