### PR TITLE
Fix nginx code closures in tabbed section

### LINKED ISSUE #259: Typo in "Authentication & HTPPS"
_Under "Adding the Certificates to Your Proxy Server"  The edits to the config file currently read:_

The certificate and key should have been placed in /etc/ssl/. NGINX needs to be told where these files are and then enable the reverse proxy to direct HTTPS traffic. In the NGINX configuration, place the following underneath your server_name variable:

`nginx ssl_certificate /etc/ssl/openhab.crt; ssl_certificate_key /etc/ssl/openhab.key;`

_Instead, it should be:_

The certificate and key should have been placed in /etc/ssl/. NGINX needs to be told where these files are and then enable the reverse proxy to direct HTTPS traffic. In the NGINX configuration, place the following underneath your server_name variable:
```
ssl_certificate /etc/ssl/openhab.crt; 
ssl_certificate_key /etc/ssl/openhab.key;
```

### PR DESCRIPTION
**Pull request by BClark09**
Made them into own categories instead of bolding statements (which was a workaround for when he had <4 headings).

Fixes #259 

Signed-off-by: Ben Clark <ben@benjyc.uk>

### CODE REVIEW

**Comment by ThomDietrich** [comment]
With kais switch and extension to "security.html" the TOC for Nginx got lost (no two TOCs in one article allowed. How would you feel about a static TOC after the Nginx headline?

**Comment by BClark09** [comment]
Hi @ThomDietrich I won't have access to a machine with Jekyll to test a TOC until the weekend. Shall we merge this now and open an issue for it or are you okay to wait?

**Comment by ThomDietrich** [comment]
Ben,
No problem. I've added and tested the TOC. Now that it is finished I actually think we should have stayed with the seperate nginx.html which would be linked from here. Too late.

Please do a quick check before I merge.

**Comment by BClark09** [comment]
Awesome, looks fine to me! Thank you!

**Pull request merged**
