### PR TITLE
Added option to generate a sitemap.xml file for Google

### PR DESCRIPTION
**Pull request by MHerbst**
Signed-off-by: Martin Herbst <mail@mherbst.de>

### CODE REVIEW

**Comment by ThomDietrich** [comment]
For reference: https://help.github.com/articles/sitemaps-for-github-pages

Is the result as desired?

**Comment by MHerbst** [comment]
It seems that it will not really work with openhab-docs :-(. For some reason I did not notic it my local tests because it look like the sitemap of the foundation's site.
The URLs generated into the sitemap.xml do not contain extensions. 

After some tests I found out that this is caused by the *permalink* option in `_config.yml`:
```
permalink: /404.html
```
This options looked a bit strange to me. I have removed this line and then sitemap and generated pages were OK.

BTW: this option was entered in the wrong file. It must be set in the frontmatter of 404.md (see: https://help.github.com/articles/creating-a-custom-404-page-for-your-github-pages-site/)

I will change and commit it.

Anyway I would say that there is a bug in the sitemap plugin.

BTW: with the foundation's site it is possible to access the pages with and without extension (that's why the generated sitemap, which looks similar, works here). 
As an example, you can access the contact page with URL http://www.openhabfoundation.org/contact and also with URL http://www.openhabfoundation.org/contact.html

@kaikreuzer Do you know why this works on the foundation's site?  The site mixes both URL formats and all links are working .... Is this configured on Cloudflare?

**Comment by ThomDietrich** [comment]
(only on phone currently) links with and without extension do also work at docs. 
One example I know for sure: http://docs.openhab.org/tutorials/migration

**Comment by MHerbst** [comment]
You are right. Probably I tried it only with the local Jekyll server and there it does no work.

**Comment by MHerbst** [comment]
I really don't know what I tested yesterday evening, but now I tried it again. It is very interesting but also the Jekyll Server supports the links with and without extension. So the local test environment behaves similar to the deployed website. Also the links in the sitemap are OK. I have tried several of them and all were OK (I will leave the final test to Google ...).

I saw that links used on the website sometimes are using the extension and sometimes not. E.g. in the main menu we have these variants:

- http://docs.openhab.org/tutorials
- http://docs.openhab.org/introduction.html
- http://docs.openhab.org/developers

All three would work with and without extension. 

But there is another point, that is more important. All pages can be addressed by at least two different URL.s. For some page there are even three valid URLs:

- http://docs.openhab.org/tutorials/
- http://docs.openhab.org/tutorials/index.html
- http://docs.openhab.org/tutorials/index

I would not even think about changing the permalink formats, because this would lead to lots of 404 errors due to the many links to pages on docs.openhab.org.

But Google does not really like these "duplicates". This will be solved by the sitemap.xml. But to be sure we should also generate a canonical link into the header of each page that contains the preferred URL. I can add this tomorrow to _includes_header.html. 

BTW: I saw that each page contains some Twitter Javascript at the bottom. I think we should remove it.

**Comment by ThomDietrich** [comment]
Hello Martin,

> in the main menu we have these variants

The main menu could just be the only menu I didn't touch in #148.

> I would not even think about changing the permalink formats, because this would lead to lots of 404 errors due to the many links to pages on docs.openhab.org.
> But Google does not really like these "duplicates".

Which links are we talking about? I would not expect too many problems from that. In #148 I've addressed a similiar problem this way: https://raw.githubusercontent.com/openhab/openhab-docs/gh-pages/features/items.md -> Could be a solution

> But to be sure we should also generate a canonical link into the header of each page that contains the preferred URL. I can add this tomorrow to _includes_header.html.

Sounds good ;)

> BTW: I saw that each page contains some Twitter Javascript at the bottom. I think we should remove it.

I think so too.

**Comment by MHerbst** [comment]
Hi Thomas,

> Which links are we talking about? I would not expect too many problems from that. In #148 I've addressed a similiar problem this way: https://raw.githubusercontent.com/openhab/openhab-docs/gh-pages/features/items.md -> Could be a solution

I was talking about the pages that could be accessed with and without .html extension. The only thing that we need to avoid problems with google is to add a canonical link to each page. But in general it looks better it the site uses the same link format (without .html) in the menus and the internal looks.
Last week while modifying the Foundation website I learned that the possibility to access pages with our without extension seems to be a Cloudflare configuration. Kai and I also had to find out that some links in the deployed page behaved different than in the Jekyll test environment.

Since monday evening the Foundation website works perfectly with https. Next week I will check again my modifications in this PR. We will also have to add a privacy policy page with the possibility to opt-out from Google Analytics (we can copy it from the foundations's site) and an imprint (it's in work).

**Comment by ThomDietrich** [comment]
Hi Martin,
did you want to add more to this PR or can it be merged?

**Comment by MHerbst** [comment]
Hi Thomas,
I would like to add the canonical links. Will be probably ready this afternoon.

**Comment by ThomDietrich** [comment]
Great. Okay I'll wait then.

**Comment by MHerbst** [comment]
@ThomDietrich Ready to merge now :-)

**Pull request merged**
