### PR TITLE
Remove reference to importing .things file configuration

### PR DESCRIPTION
**Pull request by digitlength**
.things files cannot be bulk imported

### CODE REVIEW

**Comment by Confectrician** [comment]
Hey @ digitlength this has already been solved by #1355, you have possible had an outdated version of the docs repository in your fork.

**Comment by digitlength** [comment]
> Hey @ digitlength this has already been solved by #1355, you have possible had an outdated version of the docs repository in your fork.

How often do the docs get updated? All I did was click the link at the bottom of the relevant page, which at the time still had the issue.

**Comment by Confectrician** [comment]
Sorry you are totally right.
That happens when one doesn't look close enough.

In #1355 there was a fix for line `41` of the file.
You are editing line `135`.
I simply didn't see that this was another occurrence of the wrong explanation.
I just thought "hey i have merged this some days ago" and started searching.
Finding the exact identical change without looking at the line number the case was pretty clear to me.

Sorry again and thanks for giving feedback again.

About your question:
Docs are not being transferred to the website on demand.
This happens on different triggers, like when openHAB Distro is build we are starting to fetch the latest addon doc changes automatically.

There is a high chance that a website build will be some days after the actual doc change has been merged here.
Usually that's not a problem, but especially in times of a fresh release many people loock (and/or contribute) to the docs in parallel.

**Comment by digitlength** [comment]
Ah, that makes sense: I was starting to doubt whether I'd actually sobered up from Christmas...

Thanks for all you do!

**Review by Confectrician — APPROVED** [review]

**Pull request merged**
