### PR TITLE
Generate addon docs as Jekyll Collections instead of Jekyll Pages

### PR DESCRIPTION
**Pull request by watou**
[Jekyll collections](https://jekyllrb.com/docs/collections/) are more suitable to the generated add-on docs than pages, so they can be easily traversed when generating indices or menus, or creating custom layouts.  All add-on pages have all information in each add-on's front matter, so .csv or other `_data` files aren't needed.  Also, it's less likely that people will mistakenly submit PRs against add-on docs in this repo.

Only slight "ugly" at the moment is that some ESH docs have Jekyll preambles in them which get rendered, but I think it's minor and will be resolved when the ESH docs are updated.

Reviewers: you might have to  `git pull --recurse-submodules`, then do `./update.sh` and `jekyll serve` to test.  When I did that, and diff'd the resulting `_site` directories, I only saw expected changes. All the URLs are the same as before the PR.

Signed-off-by: John Cocula <john@cocula.com>

### CODE REVIEW

**Comment by watou** [comment]
Last commit added back add-ons to the user menu, except for bindings, to address concerns from @ThomDietrich and @ShaunCurrier here: https://github.com/openhab/openhab-docs/pull/332#issuecomment-282096112.  Using Jekyll Collections makes this clean and simple.

image

Depends on https://github.com/openhab/org.openhab.ui.habpanel/pull/155 to show correct label for HABPanel.

**Comment by ThomDietrich** [comment]
This looks amazing @watou!
You've really done a great job improving the add-ons category. Kudos for that!
I'll review and merge this evening.

**Comment by watou** [comment]
Thanks very much @ThomDietrich.  I don't have doubts that this PR works correctly, but if you could pull the PR and build and test it yourself, that would be much appreciated!

**Comment by ThomDietrich** [comment]
Went through the changes and got to know how collections work. Everything looks fine to me. I did not find any problems (not that I expected that). Merging.

I'm still not happy with the bindings menu situation. Comparing he current state with the reintroduced Actions/Persistence menus, I have to say that I'd really like the same thing back for Bindings.

**Pull request merged**
