### PR TITLE
Remove Bintray References (2.5.x)

### PR DESCRIPTION
**Pull request by BClark09**
Signed-off-by: Ben Clark <ben@benjyc.uk>

### CODE REVIEW

**Review by Confectrician — APPROVED** [review]
Thanks 👍

**Comment by BClark09** [comment]
Hi @Confectrician, it seems that these changes have not applied. 

https://v2.openhab.org/docs/installation/linux.html#package-repository-installation

Have I done something wrong?

**Comment by Confectrician** [comment]
Maybe we have to rebuild the website manually due to our last structural changes.
I will try a manual rebuild and check if this solves the problem.

**Comment by Confectrician** [comment]
Jenkins was still deactivated for 2.5.x contents. (Probably because of our openHAB 3 changes.)
I have reactivated the job and started a manual website build. 

Changes are live now. Sorry for the confusion.

**Pull request merged**
