### PR TITLE
Logo for [sunsynk] Initial contribution

### PR DESCRIPTION
**Pull request by LeeC77**
Logo for [sunsynk] Initial contribution [#16753](https://github.com/openhab/openhab-addons/pull/16753#event-14221752903)

Signed-off-by: LeeC77 <lee.charlton00@gmail.com> (github: LeeC77)

### CODE REVIEW

**Comment by stefan-hoehn** [comment]
Can you please 
- link the implementation PR, so I know when this is finished
- change the title: why does it contain #16753 #1 #2404 ?

**Comment by LeeC77** [comment]
Name changed, link to already merged PR added

**Comment by stefan-hoehn** [comment]
We actually prefer svgs. I research a bit and found this one:
brand-sunsynk

or by stripping away the name part

brand-sunsynk-logo

**Comment by LeeC77** [comment]
Really though what I had proposed was an SVG, I even shrank the size as described in the Docs. The file content in code view is "`<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512"....`

Happy however if you wish to submit the file you created and reject this.

**Comment by stefan-hoehn** [comment]
my bad, sure, yours was an svg as well. I again searched for sunsync logos and it seems it is rather inverted (like the one I provided) than yours but you are more familiar than I with that company than I am. So I trust you and it is up to you: let me know if you want to keep yours or take one of the inverted ones above (I think it is easier if you download what I proposed from the PR and you change the PR yourself then).

**Comment by LeeC77** [comment]
Will  add new icon in new pull request

**Comment by stefan-hoehn** [comment]
Why did you not just replace it here?
Should I close this one now?

**Comment by LeeC77** [comment]
Could not work out how.

**Pull request closed without merging**
