### PR TITLE
Update linux.md

### PR DESCRIPTION
**Pull request by whopperg**
Updated URL and Filename to match with new version.

Also, this script copies all subdirs from userdata. But aren't there files that are important from the new release? f.e. /userdata/etc/version.properties

I use this file to display the current build i'm running as an item in my sitemap.

### CODE REVIEW

**Comment by ThomDietrich** [comment]
Hey @whopperg thanks for taking on the manual installation. Now that I look at it, the version 2.1.0 SNAPSHOT should also be used above in the installation instructions. After that's done I believe it would actually be more consistent, if the Upgrade instructions would ask the user to take "the download URL from above" instead of just giving the one as an example. What do you think?

> Also, this script copies all subdirs from userdata. But aren't there files that are important from the new release? f.e. /userdata/etc/version.properties

You are right and @BClark09 is working on a script for that. So I believe you don't have to change details regarding that just now.

**Comment by BClark09** [comment]
> @BClark09 is working on a script for that.

He is? :stuck_out_tongue: I'll see what I can in the weekend.

**Comment by whopperg** [comment]
@ThomDietrich :
Hm, i guess the "best" way would be if we dont have any version numbers in the urls or filenames at all ;-) If so, this would be always consistent thru out the lifetime of openHAB2. 
Also would it be easier for unexperienced users like me to just "copy & paste" this to a shell / script instead of looking to a bunch of code to find the place where to but this (or a variable of some kind).
But i'll guess thats not an option?

@BClark09 :
Well - i did allready put some effort into this. Feel free of using this:

`#!/bin/bash
# An error exit function
function error_exit
{
	echo "$1" 1>&2
	exit 1
}

# Using error_exit

# backup current installation with settings
TIMESTAMP=`date +%Y%m%d_%H%M%S`;
RELEASE='2.1.0';
# stop openhab2 service
echo "############################################"
echo "Stopping openHAB2 service..."
echo "############################################"
echo ""
# use systemctl or the direct path to stop the service
sudo systemctl stop openhab2.service
sudo /etc/init.d/openhab2 stop
if [ $? -ne 0 ]; then
	echo "############################################"
	error_exit "Error while stopping the service."
	echo "############################################"
	echo ""
else
	echo "############################################"
	echo "Service stopped."
	echo "############################################"
	echo ""
fi

# backup current installation
if cd /opt/openhab2; then
	if cd /opt/backup; then
		echo "############################################"
		echo "Moving current installation to Backup Folder: /opt/backup/backup-oh2-"$TIMESTAMP
		echo "############################################"
		echo ""
		sudo mv /opt/openhab2 /opt/backup/backup-oh2-$TIMESTAMP
	else
		echo "############################################"
		echo "Backup Folder does not exist. Creating..."
		echo "############################################"
		echo ""
		sudo mkdir /opt/backup
		echo "############################################"
		echo "Moving current installation to Backup Folder: /opt/backup/backup-oh2-"$TIMESTAMP
		echo "############################################"
		echo ""
		sudo mv /opt/openhab2 /opt/backup/backup-oh2-$TIMESTAMP
	fi
	else
		echo "############################################"
		error_exit "Error: openHAB2 folder not found."
		echo "############################################"
		echo ""
fi

# download new version
echo "############################################"
echo "Trying to download current release..."
echo "############################################"
echo ""
if cd /tmp; then
	cd /tmp
#	rm openhab-*-SNAPSHOT.zip
	if [ -f "/tmp/openhab-$RELEASE-SNAPSHOT.zip" ]; then
		echo "############################################"
		echo "Allready downloaded - skipping download."
		echo "############################################"
		echo ""
		echo "############################################"
		echo "Extracting current Snapshot of openHAB2..."
		echo "############################################"
		echo ""
		sudo unzip openhab-$RELEASE-SNAPSHOT.zip -d /opt/openhab2

	else
		echo "############################################"
		echo "Downloading current Snapshot of openHAB2..."
		echo "############################################"
		echo ""
		wget https://openhab.ci.cloudbees.com/job/openHAB-Distribution/lastSuccessfulBuild/artifact/distributions/openhab/target/openhab-$RELEASE-SNAPSHOT.zip
		echo "Extracting current Snapshot of openHAB2..."
		sudo unzip openhab-$RELEASE-SNAPSHOT.zip -d /opt/openhab2
		echo "############################################"
		echo "deleting openhab-$RELEASE-SNAPSHOT.zip"
		echo "############################################"
		echo ""
		rm openhab-$RELEASE-SNAPSHOT.zip
	fi
else
	echo "############################################"
	echo "TMP Folder does not exist. Creating..."
	echo "############################################"
	echo ""
	sudo mkdir /tmp
	cd tmp
	echo "############################################"
	echo "Downloading current Snapshot of openHAB2..."
	echo "############################################"
	echo ""
	wget https://openhab.ci.cloudbees.com/job/openHAB-Distribution/lastSuccessfulBuild/artifact/distributions/openhab/target/openhab-$RELEASE-SNAPSHOT.zip
	echo "Extracting current Snapshot of openHAB2..."
	sudo unzip openhab-$RELEASE-SNAPSHOT.zip -d /opt/openhab2
	echo "############################################"
	echo "deleting openhab-$RELEASE-SNAPSHOT.zip"
	echo "############################################"
	echo ""
	rm openhab-$RELEASE-SNAPSHOT.zip
fi

# restore configuration and userdata
echo "############################################"
echo "Restoring old configuration and userdata..."
echo "############################################"
	echo ""
sudo cp -arv /opt/backup/backup-oh2-$TIMESTAMP/conf /opt/openhab2/
sudo rsync -av --progress /opt/backup/backup-oh2-$TIMESTAMP/userdata /opt/openhab2 --exclude={cache,tmp,etc}

# fix permissions
# sudo chown -hR openhab:openhab /opt/openhab2

# restart openhab instance
sudo systemctl start openhab2.service
sudo /etc/init.d/openhab2 stop
if [ $? -ne 0 ]; then
	echo "############################################"
	error_exit "Error while starting the service."
	echo "############################################"
	echo ""
else
	echo "############################################"
	echo "Service started."
	echo "############################################"
	echo ""
fi
echo "############################################"
echo "Upgrade complete"
echo "############################################"`

**Comment by ThomDietrich** [comment]
Isn't he? Hahaha sorry. Now that I think about it, you were working on a Windows script, right!? In that case please ignore what I said. You don't have to

**Comment by ThomDietrich** [comment]
@BClark09 could you link the correct issue, I'm not able to find it.

**Comment by BClark09** [comment]
No worries ;) https://github.com/openhab/openhab-distro/issues/299

**Comment by whopperg** [comment]
Here it is: (at least for linux manual installation)
[update.sh.zip](https://github.com/openhab/openhab-docs/files/760399/update.sh.zip)

**Comment by ThomDietrich** [comment]
@whopperg are you still working on this?

**Comment by whopperg** [comment]
Hey,
sure, but I lost the focus on this :-) So what exactly needs to be done? Should i just update the current  doc with the new url? Because there is some info missinga on how we decide which files need to be copied back to the updated installation and so on...

On the other hand, the script that I posted above is ready as my first take. I could put this in a pull request if needed.

Cheers

**Comment by ThomDietrich** [comment]
Let's not mix things. Your backup Script should go to https://github.com/openhab/openhab-distro/issues/299 or https://github.com/openhab/openhab-docs/issues/176 or even just receive it's own Pull Request in https://github.com/openhab/openhab-distro

I think what's really missing for this PR is this:

> Now that I look at it, the version 2.1.0 SNAPSHOT should also be used above in the installation instructions. After that's done I believe it would actually be more consistent, if the Upgrade instructions would ask the user to take "the download URL from above" instead of just giving the one as an example.

The exact solution is up to you ;)

**Comment by whopperg** [comment]
Ok. I hope that i get you right, if so, i just did that ;-) all url's for manual installation are now for 2.1.0 SNAPSHOT in the new pull request (this is acutally the first time i'm doing such things with git so excuse me if i get something wrong here).

**Comment by ThomDietrich** [comment]
I don't see a new PR but normally you would add new commits to this one here. Easiest by just clicking the pen symbol on the top right here: https://github.com/openhab/openhab-docs/pull/307/files

Also, please do not forget to sign your commit: https://github.com/openhab/openhab-docs/blob/gh-pages/CONTRIBUTING.md

**Comment by whopperg** [comment]
@ThomDietrich : https://github.com/openhab/openhab-distro/pull/426 :-)

**Comment by whopperg** [comment]
>  don't see a new PR but normally you would add new commits to this one here. Easiest by just clicking the pen symbol on the top right here: https://github.com/openhab/openhab-docs/pull/307/files

> Also, please do not forget to sign your commit: https://github.com/openhab/openhab-docs/blob/gh-pages/CONTRIBUTING.md

well i screwed that one up allready ;-) sorry about that. i will fix that  after work.

**Comment by ThomDietrich** [comment]
Ah this PR. I was talking about changes here...

**Comment by ThomDietrich** [comment]
@whopperg any news?

**Comment by whopperg** [comment]
Hey @ThomDietrich,
Well, i'm waiting on that [list](https://github.com/openhab/openhab-distro/pull/426#issuecomment-281139023) we're talked about a while ago...

**Pull request closed without merging**
