### PR TITLE
Add Growatt logo

### PR DESCRIPTION
**Pull request by andrewfg**
Awaiting https://github.com/openhab/openhab-addons/pull/15120

Signed-off-by: Andrew Fiddian-Green <software@whitebear.ch>

### CODE REVIEW

**Comment by andrewfg** [comment]
@lsiepel for info

**Comment by stefan-hoehn** [comment]
Do you mind making it transparent?

**Comment by andrewfg** [comment]
> Do you mind making it transparent?

The top and bottom edges are transparent. The middle is white.

**Review by stefan-hoehn — APPROVED** [review]
LGTM

**Pull request merged**
