### PR TITLE
Add 12 new logos for add-ons page

### PR DESCRIPTION
**Pull request by bracklanna**
Same logos, this time for the `master` branch.
Signed-off-by: Bracklanna <16140600+bracklanna@users.noreply.github.com>

### CODE REVIEW

**Comment by bracklanna** [comment]
I looked into going back & amending my previous commits with signatures using `git commit --amend --signature` but on consideration it looked like it might just make things more complicated.

Once this particular batch of 12 png logos has gotten into `2.5.x` and `master` I'll be careful to properly sign-off my commits.

I read this [very helpful post](https://community.openhab.org/t/dco-check-signing-off-with-github-web-editor-explanation/83330) on the DCO / sign-off dynamics at the OH Community Forums.

**Comment by Confectrician** [comment]
We could also cherry pick the logos from 2.5.x branch, since they are merged now over there.

**Comment by bracklanna** [comment]
Whatever you all  think is best. Over the coming couple of weeks I will produce another 3 or 4 batches  of updated logos. Commits for those will be signed-off.

**Comment by bracklanna** [comment]
I noticed quite a few of the new logos are up on the live website at http://openhab.org/addons (except for logos for v1 bindings, I guess the maintainers have decided not to highlight v1 bindings, which is understandable.)

I've prepped another batch of logos, ready to commit & PR. 

What should I do at this point -- just commit & PR to the `2.5.x` branch alone? Or should I also commit separately to `master`.?

**Comment by ghys** [comment]
I think @Confectrician is right - let's merge this one but in the future, just open PRs for the 2.5.x branch and we'll cherry-pick to master. Thank you @bracklanna for this initiative!

**Pull request merged**
