### PR TITLE
Restructure Tutorials, Add Community links

### LINKED ISSUE #205: Tutorials: Give a list of Tutorials and Examples
Right at the starting page of the Tutorials section or in one subcategory: http://docs.openhab.org/tutorials/

Incomplete Examples List:

* https://community.openhab.org/t/about-the-tutorials-examples-category/15581

* https://community.openhab.org/c/setup-configuration-and-use/tutorials-examples

* [Example 1](https://community.openhab.org/t/washing-machine-state-machine/15587/1), [Example 2](https://community.openhab.org/t/power-consumption-of-lights-and-more/15642/1), [Example 3](https://community.openhab.org/t/speedtest-cli-integration/7611/1), [Example 4](https://community.openhab.org/t/influxdb-grafana-persistence-and-graphing/13761), ... we should select more examples from the forum

* german blogs:
  * http://onesmarthome.de/category/openhab-2
  * https://klenzel.de/kategorie/technik/hausautomatisierung/openhab (OH1!)
  * http://www.marcsblog.de/tag/openhab (OH1!)

* english blogs:
  * http://hackaday.com/tag/openhab - http://hackaday.com/tag/home-automation
  * http://www.makeuseof.com/tag/getting-started-openhab-home-automation-raspberry-pi (OH1!)
  * http://www.makeuseof.com/tag/openhab-beginners-guide-part-2-zwave-mqtt-rules-charting (OH1!)

### PR DESCRIPTION
**Pull request by ThomDietrich**
Closes #205 

Signed-off-by: Thomas Dietrich <Thomas.Dietrich@tu-ilmenau.de>

### CODE REVIEW

**Comment by ThomDietrich** [comment]
@kaikreuzer 

2017-01-24 14_06_59-clipboard

**Comment by kaikreuzer** [comment]
Nice, thanks!

**Comment by ThomDietrich** [comment]
I've just discovered a few spelling error -.- @BClark09 would you do create PR and do general proofreading in the process? :) Thanks you!

**Comment by BClark09** [comment]
Made #265

**Pull request merged**
