### PR TITLE
Change stable Linux repository locations

### PR DESCRIPTION
**Pull request by BClark09**
Related to https://github.com/openhab/openhab-distro/issues/1256

Signed-off-by: Ben Clark <ben@benjyc.uk>

### CODE REVIEW

**Review by ecdye — APPROVED** [review]
LGTM

**Review by Confectrician — APPROVED** [review]
Thanks 👍

**Comment by BClark09** [comment]
Hi @Confectrician,

I missed updating the V2 version of the docs. Which branch can we cherrypick this PR into? `2.5.x` or `final-2.5.x`?

**Comment by Confectrician** [comment]
`2.5.x` would be the target. (final is for generated/merged contents from ci.openhab.org)

Do you want to open a PR yourself?

**Comment by BClark09** [comment]
Thanks! #1567

**Pull request merged**
