### PR TITLE
Sitemaps: Improves readability

### PR DESCRIPTION
**Pull request by bgilmer77**
Improve introductory paragraph

Signed-off-by: Brad Gilmer <brad@gilmer.tv> (github: bgilmer77)

### CODE REVIEW

**Comment by bgilmer77** [comment]
Hum - out of time for today.  Apparently my branch is out of date.  I tried to update it one way, but that failed.  Will work more on this later.

**Comment by bgilmer77** [comment]
@ThomDietrich, I could use some help with GitHub.  Here is the situation - while I was working on the items.md file, the sitemap.md file was (slightly) modified.  So my fork of this repo at bgilmer/openhab-docs does not have the most up-to-date version of the sitemap.md file.  So of course, when I post a PR with my changes, GitHub says that the branch has conflicts.

I tried editing my repo to incorporate the exact changes that had been made to the sitemap.md file here, and when I created this commit and uploaded it, the message about conflicts went away.  But as soon as I made my edits in my local file (which was exactly identical to the current version posted here) and made that commit, the message about conflicts reappeared.

What is the proper way to "refresh" your fork?  If I just delete my fork and pull down the current stuff from here, then it will blow away all of my items.md changes that have not been merged yet.  It seems that this will likely confuse GitHub Desktop, which is what I am using locally.

Any suggestions?

FWIW, once I get this figured out, I will close this PR and start over.

**Comment by Confectrician** [comment]
I am not Thom, but upstream is the solution for you.
Do you work completely in GitHub or with some editor with a git extension or something like that?

Here's something to read about the "keepiong a fork up to date" topic:
https://help.github.com/articles/syncing-a-fork/
https://gist.github.com/CristinaSolana/1885435

Please keep in mind that you want to sync different branches.

You want to update from 
openhab-docs/gh-pages branch
to

bgilmer/openhab-docs/YOURCURRENTWORKINGBRANCH

whatever that branch is called.

**Comment by bgilmer77** [comment]
@Confectrician, thanks very much!  I will look into the links you provided.

 My workflow is as follows:
- Fork from openhab/openhab-docs -> bgilmer77/openhab-docs
- In GitHub, go to bgilmer77/openhab-docs and download the repo to GitHub Desktop
- In GitHub Desktop create a new branch for each intended PR.  For example, create a branch called sitemaps-nits1 for this work where I am making a "nit" pass all the way through the sitemaps.md file.
- In Atom (with Linter extensions), edit sitemaps.md file, working on one section per commit.
- Once the first section is complete, make a commit to bgilmer77/openhab-docs using GH Desktop
- Go to bgilmer77/openhab-docs on GitHub and create a PR for openhab/openhab-docs
(Initial PR complete)
- Edit next section of sitemaps.md using Atom
- In GH Desktop perform the next commit and Push
(Rinse and repeat until finished working on the article)

**Comment by bgilmer77** [comment]
@Confectrician, one question, but first some background.

-  I have contributed a large number of tweaks to the items.md article.  These have not been merged yet.
-  While I was working on items.md, some minor changes were made to sitemaps.md, which is where I would like to work next.
Question: If I perform the actions in the links you provided, is it going to  roll back my local items.md file to the current version (which does not have my submitted changes)?  Will I lose all my work on my local repo?

**Comment by Confectrician** [comment]
>  If I perform the actions in the links you provided, is it going to roll back my local items.md file to the current version (which does not have my submitted changes)? Will I lose all my work on my local repo?

I think this depends on the changes that were made.

Here some possible cases:

1. items.md file was not updated meanwhile:
   =>Your changes are "newer" than the status you will get from syncing. Everything should be fine.
2. items.md file was updated too:
    1. The lines that were edited are others than the lines that you changed
        =>Git will merge both changes together
    2.  There are some lines that have been changed on both sides
         =>Git will show you a merge conflict and you have to explicitly choose wich change will be shown 
         after merging

To be save you could make a local copy of your items.md as a backup, since i am not 100% sure.


I think there is another way of updating your fork with the "rebase" command,
but i havent done that yet in a live environment, so i am not the right person to explain it to you.
This is something for a general talk and nothing for a PR conversation.

If you are still unsure, fell free to ask additional questions.
I will halp as far as i can. :)

**Comment by Confectrician** [comment]
And just for spreading out some knowledge:

This is exactly the reason for doing 1 sentence per line in the docs md files.
With this writing convention, we can make sure that git has the ability to check each sentence for changes and keep the amount of merge conflicts small.

**Comment by bgilmer77** [comment]
I think I have fixed this problem with the instructions at this link:
https://help.github.com/articles/syncing-a-fork/
Therefore, I am going to close this PR and open a new one, hopefully without any conflicts.

**Pull request closed without merging**
