### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by kaikreuzer**
Fixes https://github.com/openhab/openhab-docs/issues/794

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
@bgilmer77 Not sure about your concerns. We use EPL since years for all our code and this is clearly about copyrights.
You might want to read https://www.eclipse.org/legal/eplfaq.php and https://www.eclipse.org/legal/epl-2.0/faq.php, which explain the license in detail.

**Comment by bgilmer77** [comment]
@kaikreuzer I will take a look at the links.  Thank you.  I only read things quickly so I may have missed something.

**Comment by bgilmer77** [comment]
A quick read of the two links you provided and a search for the word, "copyright" seems to indicate that the links, at least, do not specifically contain information about ownership of documentation, the granting of rights WRT documentation, etc.  I will take time to read the license carefully and get back to you as quickly as I can.

**Comment by bgilmer77** [comment]
All,  I have now had a chance to get a cup of espresso and read through the EPL v2.0.  I agree that this license covers copyrights and documentation.  Interestingly, it is not clear about who owns the copyright once a contribution has been accepted, but I am not going to argue with what has been working for a long time.

If at some point in the distant future the EPL is reviewed, my comment would be to make it clear that a) the contributor owns the copyright in any contributed material, and b) the organization (us) owns the copyright in the final product.

I vote to merge.

**Comment by pfink** [comment]
> Interestingly, it is not clear about who owns the copyright once a contribution has been accepted, but I am not going to argue with what has been working for a long time. If at some point in the distant future the EPL is reviewed, my comment would be to make it clear that a) the contributor owns the copyright in any contributed material, and b) the organization (us) owns the copyright in the final product.

I think you misunderstood the concept of open source. It's not about granting copyrights to a specific person or legal entity, it's about granting copyrights to everyone. After the contribution, everybody in the world who owns the copyrights under the conditions mentioned in the license.

**Comment by bgilmer77** [comment]
Nope - did not misunderstand about Open Source.  Have been working with it for a long time.

You can't grant everyone a copyright if you do not have the right to do so (in other words, if you don't own it, you can't give it away for free to others).

Not a big deal - one can spend months/years on this.  I trust the EPL has been vetted by some of the top IPR/Copyright lawyers in the world.  I am not a lawyer, so I am 100% comfortable with the call to go with that license.

**Comment by pfink** [comment]
> You can't grant everyone a copyright if you do not have the right to do so (in other words, if you don't own it, you can't give it away for free to others).

The contributor owns the copyright of his contribution, so of course he can grant rights to everbody. If you wanted to express that just setting a license after years of contribution activity from over 100 contributors without asking for permission is a legal GAU, of course this is true, no license could help us out of this mess, also not the EPL. But I thought that was clear to everybody.

**Pull request merged**
