### PR TITLE
Added content to the Things.md configuration page (Fixes #312)

### LINKED ISSUE #312: Things: enhance configuration document
The configuration document for things is currently a stub and needs some content. I'm going to start writing a document for it to submit as a PR and I plan to cover the following at a minimum:

* Introduction
* Discovery based configuration
* File based configuration
    * Highlighting the fact that some bindings (for example, Z-Wave) do not currently work properly with things files
    * Basic syntax
    * A few key examples

Is there anything else anyone would like to see covered?

### PR DESCRIPTION
**Pull request by stephenbonar**
-Added an introduction section
-Added a things definition section
-Added a discovery based definition subsection
-Added a file based definition subsection
-Added a syntax subsection

Signed-off-by: Stephen Bonar <contactme@stephenbonar.com> (github: stephenbonar)

### CODE REVIEW

**Comment by stephenbonar** [comment]
I took a stab at writing the Things configuration section to the best of my knowledge. Considering there wasn't much documentation to use as a starting point, I did my best given what I was able to glean from community discussions, my own experience, and the Eclipse SmartHome docs. Please feel free to correct anything that may not be completely accurate or suggest adding something I may have missed!

**Comment by ThomDietrich** [comment]
Hey @stephenbonar, thanks for taking on this task!! I didn't have the time to review yet but I'll do that in the next couple of days and comment here again ;) Thanks for your contribution!

**Comment by stephenbonar** [comment]
Sounds good, thanks for the heads up!

**Comment by ThomDietrich** [comment]
Hello @stephenbonar,
this is a great start! I went through the whole article and did a few additions myself. Mostly details and formatting nitpicks. Could you please review the commit I've added!?

One topic not covered yet is the one of Bridges, this is also important because of the syntax needed in configuration files for these. I'd merge the article as soon as I hear back from you and Bridges can be topic of the next PR for this article.

Thank you for your contribution!

**Comment by kaikreuzer** [comment]
@stephenbonar Indeed an excellent documentation, thank you very much!

One feature (that is probably not yet well-known, due to the lack of documentation :-/) that escaped you is the possibility to do the item linking to existing items from the Paper UI:

There are two options, depending on the Configuration->System->Item Linking->"Simple Mode" switch:
1. Simple Mode = ON: For newly added Things, items are automatically created for all non-advanced channels and these items are automatically linked to the according channel. The Paper UI does not show any "Configuration->Items" menu, so that the existence of items is rather hidden from the user. By clicking on a channel of a thing, auto-generated item+links are created and removed.
2. Simple Mode = OFF (recommended for "real" use): No items/links are auto-created. Instead, the Paper UI offers a "+" icon for adding a link to existing items, when clicking on a channel:
screen shot 2017-03-02 at 09 22 00
Doing a "long press" on the blue circle of a not-linked channel will open a pre-filled dialog for creating a new item - this is a short cut for easily creating items with user defined labels, names, category. Not sure if this should be mentioned in the docs, though as my recommendation would still be to maintain the items in a text file. All items are additionally shown in a menu entry Configuration->Items.

Would you see a chance to add this information at a good place in your PR?

**Comment by stephenbonar** [comment]
As for Thom's suggestion about adding information about Bridges and Kai's suggestion about adding information about Item linking, I think we can include information on both. Should we just go ahead and merge what we have so far and then create a new PR to include these changes?

**Comment by ThomDietrich** [comment]
I'd agree. Let's merge and continue from there. One more todo I'd like to add is a detailed description of the syntax itself. Currently there are only a few examples and a description for them. Would be good to have a concrete syntax definition first.

@stephenbonar are you going to continue your excellent work on Things?
Thanks for the contribution so far!

**Pull request merged**
