### PR TITLE
Added JSR223 subpages to nav menu

### PR DESCRIPTION
**Pull request by steve-bate**
Signed-off-by: Steve Bate <svc-github@stevebate.net> (github: steve-bate)

### CODE REVIEW

**Comment by steve-bate** [comment]
@ThomDietrich I'm not sure what I'm doing wrong, but the submenu items for the language-specific JSR223 pages are not being shown when the expansion handle is clicked.

**Comment by ThomDietrich** [comment]
Heyho!
You ran into one of the docs page quirks. Menus are only extended down to the point the currently shown page is referenced. Submenus are not extended. Pay attention to the "Overview" article in all other menu branches.

I've touched the page design a few times already but every time I feel the strong urge to just delete the css and javascript files and start from the beginning (maybe even without a starter template). Sadly I do not have the time to take on such a big project in the next 12 months. I've got many ideas how the new page would look like and I've already tried to recruit 1-2 media technology students for the job... without success :) Maybe we can ask for help in the community. I know that there are a few people out there willing to help but without the Java skills to help with serious openHAB development.

Off topic. Anyhow, either ignore the issue or add an overview link. Alternatively we could modify the way the menu extends: https://github.com/openhab/openhab-docs/blob/gh-pages/js/init.js#L61-L65

**Comment by ThomDietrich** [comment]
@steve-bate should I merge as is?

**Comment by steve-bate** [comment]
It doesn't hurt anything. I'm not an experienced Javascript developer so I won't be able to fix the existing menu issue anytime soon.

**Comment by ThomDietrich** [comment]
It's okay. As I said we need another solution for this. Off topic. I'll go ahead and merge.

**Pull request merged**
