### PR TITLE
Add logo for Energi Data Service binding

### PR DESCRIPTION
**Pull request by jlaur**
This logo is for openhab/openhab-addons#14376

### CODE REVIEW

**Comment by stefan-hoehn** [comment]
@jlaur Jacob, is it intended that the logo is cropped at the right hand side?
image

**Comment by jlaur** [comment]
> Jacob, is it intended that the logo is cropped at the right hand side?

Can you elaborate? I think it's cropped in both sides intentionally, do you see anything special at the right side?

**Comment by stefan-hoehn** [comment]
my bad, due to the right characters being so tight to the right margin, I was thinking, something was missing. I should have looked more closely. All good, Jacob

**Comment by jlaur** [comment]
> It is still in draft, which is why I should't merge it yet, right?

Yes, unfortunately it seems no one has had time tp pick up the binding PR for review yet.

**Comment by Confectrician** [comment]
No Problem from docs side.
Just leave it as a draft, until the addon PR has been merged. 🙂

**Comment by jlaur** [comment]
@Confectrician, @stefan-hoehn - openhab/openhab-addons#14376 was just merged. 🙂

**Review by stefan-hoehn — APPROVED** [review]
@jlaur "message understood" 😊, sorry for the delay. Thanks.

**Pull request merged**
