### PR TITLE
replace .calendar with .zonedDateTime

### PR DESCRIPTION
**Pull request by Rosi2143**
getCalender() is deprecated getZonedDateTime() should be used

### CODE REVIEW

**Comment by Confectrician** [comment]
Thanks for jumping in with this improvement.
Did you check other files too for instances of getcalendar()?

**Comment by Rosi2143** [comment]
Hi,

no not yet. I will check when I'm back home.

**Comment by Confectrician** [comment]
>no not yet. I will check when I'm back home.

It's not urgent, but would be a good chance to improve this global in the docs.
We can merge this PR righ away and check it in a second step, if you need more time. :)

**Comment by Rosi2143** [comment]
I checked now and did not find any other place with getCalender -- yet.

**Pull request merged**
