### PR TITLE
Small typo fix in Manipulating Item States

### PR DESCRIPTION
**Pull request by JMacIV**
Didn't look through much else, just noticed this typo quickly.

### CODE REVIEW

**Comment by JMacIV** [comment]
Is it possibly to do the DCO check from web interface of GH? I ask since I did not have the docs saved locally and only edited using web editor. 

I think I was able to sign the commit message after saving to local. But am not sure if how to force the check again.

**Comment by openhab-5iver** [comment]
When submitting through GH, you can add the sign-off only in the orginal commit, and can't add it in later through the website. There is a small fix exception though, so you shoud be fine. Still good to add the sign-off to at least the PR. For larger changes, you can fork the repo and then use the git commands listed to amend the commit (see the Details next to the DCO check).

**Comment by JMacIV** [comment]
> When submitting through GH, you can add the sign-off only in the orginal commit, and can't add it in later through the website. There is a small fix exception though, so you shoud be fine. Still good to add the sign-off to at least the PR. For larger changes, you can fork the repo and then use the git commands listed to amend the commit (see the Details next to the DCO check). Thank you for improving the docs... every little bit helps!

Ahh gotcha. Thanks @openhab-5iver ! Most of my GH experience has been for my own repos with just me in them, so didn't sign anything off. 

I will keep that in mind about signing off during initial commit for any further editing of the docs when I catch something. May try to look into the docs a little more later to help that way since my Java is basically non-existent. 

I did fork repo and apply git commands from DCO right before I made my first comment, but not sure if I actually did it correctly. Thought I did, but have been wrong before!

**Comment by openhab-5iver** [comment]
> I did fork repo and apply git commands from DCO right before I made my first comment, but not sure if I actually did it correctly.

There hasn't been an update to the commit. Did you do both steps? When it works, your commit will look like this... https://github.com/openhab/openhab-docs/commit/62b4dcfc3b9f5389749ee9ab5f26d635f8f3451d.

**Comment by JMacIV** [comment]
@openhab-5iver Got it now! Thank you for following up and helping to teach me!

When I ran the second command, git push, I guess it did not fully execute or something previously. I just ran them both again, first one looked fine like before. But the git push (I copy and pasted from the DCO page on the first attempt, then just hit the up button in terminal to get back to that command) looked completely different on second run. 

Not sure why it didn't run correctly in the first place? But looks good to go now, right?

**Comment by openhab-5iver** [comment]
> Not sure why it didn't run correctly in the first place? But looks good to go now, right?

Yes, and DCO check is passed!

**Comment by JMacIV** [comment]
> > Not sure why it didn't run correctly in the first place? But looks good to go now, right?
> 
> Yes, and DCO check is passed!

Heck yeah!!! Slowly learning... Thanks again, appreciate all that you do! Have seen your name around the forums enough to know that it is a lot!

**Comment by JMacIV** [comment]
> Hey @JMacIV
> 
> Thanks for your contribution and also thanks for taking care of the sign-off directly. 🙂
> 
> Everything fine here.
> 
> BR
> Jerome

Glad to hear it, Jerome! Appreciate you! Will make sure any other contributions from me require less explanation (at least for the docs!)

**Comment by Confectrician** [comment]
You're welcome.

No need to worry. 🙂 
No one can learn everything from scratch and we all here like to help if there are any questions.
So if something seems confusing or is not clear, just ask.

**Pull request merged**
