### PR TITLE
tip if you installed from openHABian

### PR DESCRIPTION
**Pull request by erichgoldman**
I did a quick setup on rPI using openHABIAN per --> https://www.openhab.org/docs/installation/openhabian.html#raspberry-pi-prepackaged-sd-card-image . Coluld not access via SSH using these instructions, found this and was able to get in to start editting files remotely. Maybe additional information is needed for this note?

### CODE REVIEW

**Comment by ThomDietrich** [comment]
Wouldn't it be easier and clearer if you added this note directly to line 58?

**Comment by BClark09** [comment]
I don't think this section talks about the same thing you've added.

In the docs you've edited, it is talking about accessing the openHAB console via SSH and *not* the machine that has openHAB installed. Same protocol, but accessing different things.

The page you linked to does contain the information you seek:

> Ready for more? Connect to your Raspberry Pi SSH console using the username openhabian and password openhabian. You will see the following welcome screen:

But perhaps this can be made clearer?

**Comment by ThomDietrich** [comment]
Ben is totally right. Ignore my previous comment.

I feel like this paragraph (with the visual highlighting of the password ) is already pretty clear. But that might just be the proud author speaking 😋

**Comment by erichgoldman** [comment]
New to openHAB so not sure exactly sure what is supposed to be here. I believe I was looking to connect to upload a file or view a log. When searching for SSH I found this page. 

Should those instructions and logins work on openHABian as well? That port wasn't open and those credentials did not work for me. Is this something which isn't part of the openHABian install or should I be able to access this console on my installation with these creds?

**Comment by erichgoldman** [comment]
To follow the docs, I sshed with openhabian, then ran `openhab-cli console` so I think that then puts me at the same place.

**Comment by ThomDietrich** [comment]
Hey Eric,
you simply ended up in the wrong article.
However, that we should avoid by making clear that what you found is not what you are looking for. Looking at the console page I see this:

image

I would propose you come up with a solution that reduces the risk this is wrongfully understood as the way to login to your system via SSH. I'd suggest a headline like "Remote Connection" instead of "Connecting via SSH" and starting the article with something like "The openHAB console offers the option to:". This and maybe 2-3 more changes should make clear that this article is specific to the console (an advanced interface of openHAB) rather than the SSH console of your host system (e.g. openHABian).

While at it, Could I ask you to move the note block before the code block with `ssh -p 8101 openhab@localhost`?

**Comment by ghys** [comment]
Note: changed the base branch to `2.5.x` which is the default for now, and will appear on the production website.
`master` is now the branch for openHAB 3.x docs.

@openhab/documentation-maintainers 
Once this is merged to `2.5.x` please remember to merge (for example, cherry-pick the commit) this to `master` as well if appropriate.
See https://github.com/openhab/openhab-docs/issues/1133 for details.

**Comment by mstormi** [comment]
Obsoleted by changes made in the meantime
@Confectrician pls close

**Comment by Confectrician** [comment]
> Obsoleted by changes made in the meantime
> @Confectrician pls close

**Pull request closed without merging**
