### PR TITLE
[sitemap] New Slider parameter releaseOnly

### PR DESCRIPTION
**Pull request by mueller-ma**

### CODE REVIEW

**Comment by lolodomo** [comment]
We could also explain in introduction the two different modes and what is the default behaviour (with the particular case of element generated for group member).

**Comment by mueller-ma** [comment]
What exactly is the behavior when `releaseOnly` isn't set?

**Review by stefan-hoehn — APPROVED** [review]
LGTM, thx

**Comment by lolodomo** [comment]
I will probably create an additional PR later. But the minimum is already here now.

**Pull request merged**
