### PR TITLE
Fix tabs and indention in _includes and _layouts

### PR DESCRIPTION
**Pull request by ThomDietrich**
Code style fixes convenient before I start to work on the new docs structure. Formatting was fixed in the Atom editor with default settings.

Compare ``diff`` with and without whitespaces:
https://github.com/openhab/openhab-docs/pull/147/files
https://github.com/openhab/openhab-docs/pull/147/files?w=0

Additionally: Some HTML fixes, a testing file for redirection I'll need for the next step.

@kaikreuzer a quick "okay with me" would be nice ;)

Signed-off-by: Thomas Dietrich <thomas.dietrich@tu-ilmenau.de> (github: ThomDietrich)

### CODE REVIEW

**Comment by hakan42** [comment]
For people who don't use Atom editor with default settings (whatever that might be 😄 ), could you perhaps add a editorconfig file to this repository? The all our editors would keep the same formatting:

http://editorconfig.org/

**Comment by ThomDietrich** [comment]
I've added this information purely to underline that the changes follow a certain style guide. For me it was more important to have some consistency *now*. Further additions will hopefully follow the established style. But yes sure, I can add a editorconfig file while we are at it.

**Comment by ThomDietrich** [comment]
@hakan42

**Comment by ThomDietrich** [comment]
After @hakan42 didn't have any other complaints and as my local representation seems to be working, I'll go ahead and merge.

**Pull request merged**
