### PR TITLE
Explain new UoM system

### PR DESCRIPTION
**Pull request by J-N-K**
Related to https://github.com/openhab/openhab-core/pull/3481

### CODE REVIEW

**Review by stefan-hoehn — APPROVED** [review]
Thanks for the comprehensive explanation, Jan. LGTM.

**Comment by J-N-K** [comment]
I did nothing :-) Maybe GitHub selected that automatically.

**Comment by lolodomo** [comment]
The documentation is clear now, thank you.
I see just one thing missing. We should explain to the user what unit he will get in rules for any item state. It is implicit but I think it will be better to say it.
The following sentence could be enhanced: "The state description is used for display purposes only, it can contain any compatible unit and will not affect what is persisted or used in events."
Proposal: The state description is used for display purposes only, it can contain any compatible unit and will not affect what is persisted or used in events **and rules**.
WDYT ?

**Comment by stefan-hoehn** [comment]
Would it even make sense to change the following in the UI

image

to 

Pattern or transformation applied to the state ONLY for display purposes?

**Pull request merged**
