### PR TITLE
Added note about automatic java install

### PR DESCRIPTION
**Pull request by BClark09**
Signed-off-by: Ben Clark <ben@benjyc.uk>

### CODE REVIEW

**Comment by ThomDietrich** [comment]
Do you want to merge this PR right away, even if these instructions are for latest snapshots?

**Comment by BClark09** [comment]
What's the best practice? To only have documentation relating to the most common release (stable) or say "From version 2.2.0..." I'm inclined to think that the latter would just confuse people into thinking "There's a new version?!"

**Comment by ThomDietrich** [comment]
Maybe.
We were actually already discussing (in another thread) to add different version snapshots of the documentation. This is not yet implemented and might take a few more days...
The change in this PR is rather uncritical but we should keep that in mind.
Let's merge.

**Comment by BClark09** [comment]
Ah, that sounds good! Will have a look for that. 

> Last comment: Is the ":" at the end a typo?

Yes :stuck_out_tongue:

**Comment by ThomDietrich** [comment]
Full Stop ^^

**Pull request merged**
