### PR TITLE
visualcrossing logo

### PR DESCRIPTION
**Pull request by magx2**
https://github.com/openhab/openhab-addons/tree/main/bundles/org.openhab.binding.visualcrossing

### CODE REVIEW

**Comment by stefan-hoehn** [comment]
2 questions:
- Has this binding been already implemented and do you mind adding a link to the binding in the description?
- Would you mind looking for an SVG version of the logo?

**Comment by magx2** [comment]
1. done
2. there is none

**Comment by magx2** [comment]
@stefan-hoehn ping

**Comment by stefan-hoehn** [comment]
I will merge this now. 

However, do you mind having a look at the readme of the binding? It sounds like a marketing text that was copied from their website (it uses the word  "our" several times for example). Please be so kind and change the text, so it describes it rather from your perspective than theirs. Thanks.

**Review by stefan-hoehn — APPROVED** [review]

**Comment by magx2** [comment]
> It sounds like a marketing text that was copied from their website (it uses the word "our" several times for example)

I've copied it from their website and put it in quotes so using "ours" is not a problem, because everyone knows that it's VS statement not ours.

 > Please be so kind and change the text, so it describes it rather from your perspective than theirs.
 
 It's just another weather binding. I've wrote `VisualCrossing Binding provides integration with VisualCrossing API` and added link to their site. There is nothing more to add

**Pull request merged**
