### PR TITLE
Fix typo in beginners tutorial

### PR DESCRIPTION
**Pull request by AngelosF**
Closes https://github.com/openhab/openhab-docs/issues/605
extra small change, no need to signoff :)

### CODE REVIEW

**Comment by bgilmer77** [comment]
Hi @AngelosF,  already have #603 open, and in that PR I have corrected a number of linter errors and made other changes as well.  Are you okay with me incorporating your change into my PR and closing this one?

**Comment by Confectrician** [comment]
I would prefer your approach too @bgilmer77.

You have already changed several files and updated the linter part, so line numbers would conflict with this change.

**Comment by bgilmer77** [comment]
Okay - but I wait for @AngelosF

**Comment by bgilmer77** [comment]
Hi @AngelosF.  I have put your changes into PR #603, and this has been reviewed by @Confectrician.  The changes have been merged.  Accordingly I will close this PR.  If there is an issue with this, please let me know.

**Pull request closed without merging**
