### PR TITLE
Installation instructions for Armbian

### PR DESCRIPTION
**Pull request by igorpecovnik**
Initial commit.

Please squash commits on merge since it was edited online/history looks ugly and is not relevant.

### CODE REVIEW

**Comment by Confectrician** [comment]
Additional information:

We have to add the armbian.md file to the vuepress config here and in the website repository, as soon as this pr has been merged.
Therefore i have tagged the dependency label some days ago.

**Comment by Confectrician** [comment]
> Please squash commits on merge since it was edited online/history looks ugly and is not relevant.

Yes. We always squash and merge here. 🙂

**Comment by igorpecovnik** [comment]
> We have to add the armbian.md file to the vuepress config here and in the website repository

Thanks for clarification.

**Comment by Confectrician** [comment]
I am currently solving some build problems and will merge this PR as soon, as this is finished.
I will also take care of adding the sidebar entries. :)

**Pull request merged**
