### PR TITLE
Delete word "fully" from introduction.md

### PR DESCRIPTION
**Pull request by bgilmer77**
-  Delete word "fully" from introduction.md
Signed-off-by: Brad Gilmer <brad@gilmer.tv> (github: bgilmer77)

### CODE REVIEW

**Comment by bgilmer77** [comment]
This commit is a test to ensure that I have my git workflow working properly.

**Comment by ThomDietrich** [comment]
Two things I have to mention are 1. you've missed the Sign-Off and 2. your git message is not ideal.
See: http://chris.beams.io/posts/git-commit/

You can still fix this now, Below this message you'll find the Merge button. Select "Squash and merge" and you'll be able to change both the commit message and the description.

@bgilmer77 @Confectrician "Squash and merge" should be the normal action, "Rebase and Merge" is also okay, never use the classic "Merge Commit" approach. Also remeber that commit messages here in thedocs repo always contain the article/area a change was made in, see: https://github.com/openhab/openhab-docs/commits/gh-pages

**Comment by Confectrician** [comment]
@bgilmer77 are you working from console in your new setup?

I want to mention the `git commit -s` parameter again.

Maybe there is an atom package or something like this that adds this option to the atom GitHub view.

**Comment by bgilmer77** [comment]
@ThomDietrich @Confectrician Thanks to both of you.  I will fix the things you mentioned above.

**Pull request merged**
