### PR TITLE
Add official logo for Miele Cloud binding

### PR DESCRIPTION
**Pull request by BjoernLange**
Adds the official Miele logo (for the Miele Cloud binding).

### CODE REVIEW

**Review by Confectrician — APPROVED** [review]
Thanks 👍

Will get merged when openhab/openhab-addons#9146 got merged too.

**Comment by BjoernLange** [comment]
Hi @Confectrician! Just to let you know: openhab/openhab-addons#9146 got merged yesterday.

**Comment by Confectrician** [comment]
Thanks for the ping @BjoernLange, I had the PR on watch anyway. 🙂

**Review by Confectrician — APPROVED** [review]
Thanks 👍

**Pull request merged**
