### PR TITLE
[huesync][binding][logo] Add logo for huesync binding to repository

### LINKED ISSUE #2407: [huesync][binding][logo] Add logo for huesync binding to repository
Depends on PR \#16516 **[huesync] [Hue Play HDMI Sync Box Binding](https://github.com/openhab/openhab-docs/pull/2408)**

### PR DESCRIPTION
**Pull request by pgfeller**
Fixes #2407

Signed-off-by: Patrik Gfeller <patrik.gfeller@proton.me>

### CODE REVIEW

**Comment by lsiepel** [comment]
Ready: (https://github.com/openhab/openhab-addons/pull/16516)

**Comment by stefan-hoehn** [comment]
Why do we have both #2407 and #2408? I am confused 😄

**Comment by lsiepel** [comment]
> Why do we have both #2407 and #2408? I am confused 😄

Haha 2407 is an issue 2408 a PR. In most repo’s we prefer to have an issue (for discussion) before the PR. Guess @pgfeller followed that ‘habit’, but yes not needed for this repo.

**Review by stefan-hoehn — APPROVED** [review]
Thanks, Patrik, lgtm

**Comment by stefan-hoehn** [comment]
> Haha 2407 is an issue 2408 a PR.

In german we say "Wer lesen kann ist klar im Vorteil" ("Those who can read have a clear advantage") 😜 Thx, I should have looked a bit more closely 😅

**Pull request merged**
