### PR TITLE
[profiles] Update index.md

### PR DESCRIPTION
**Pull request by udo1toni**
For consistency, existing system profiles need keyword `system:`

### CODE REVIEW

**Comment by jimtng** [comment]
I like not having to type so much and if a plain "follow" works without "system:follow" why not? It was implemented in core to allow it and "forcing" / documenting otherwise would negate that benefit.

**Comment by udo1toni** [comment]
The point is, it's different in the items documentation: https://www.openhab.org/docs/configuration/items.html#profiles

**Comment by jimtng** [comment]
Just to update my findings here as well (I did write about it on the forums too): core will tolerate it without "system:" but it will log an info message. Maybe we should ask @openhab/core-maintainers about which one is preferred here?

**Comment by stefan-hoehn** [comment]
@jimtng So the docu change here is fine for you?

**Comment by jimtng** [comment]
Yes

**Review by stefan-hoehn — APPROVED** [review]

**Pull request merged**
