### PR TITLE
Optimize all png images using zopflipng

### PR DESCRIPTION
**Pull request by ecdye**
The command
``` bash
for i in $(find . -name '*.png'); do zopflipng -m --filters=0me --lossy_8bit --lossy_transparent -y "$i" "$i"; done
```
was used to accomplish this optimization, all images should have lost no
accuracy as a result of the compression applied.

Signed-off-by: Ethan Dye <mrtops03@gmail.com>

### CODE REVIEW

**Comment by Confectrician** [comment]
Did you check out the preview page and look around a bit in the articles?

I have done so for some pages and did not see any cruel things so far.

**Comment by ecdye** [comment]
> Did you check out the preview page and look around a bit in the articles?

Yes I have.

> I have done so for some pages and did not see any cruel things so far.

I didn't observe anything either, which is exactly how it should be. :smile:

**Comment by ecdye** [comment]
I will say that I will be making updates to the quality of other icons in the future as well, this is merely a bandwidth saving measure for the moment with many of the images that we serve up.

**Comment by Confectrician** [comment]
>On that tangent, is there any reason that we can't use svgs for the add-on logos when available?

Not from my knowledge. So we should just try it out and see what't the outcome.

**Review by Confectrician — APPROVED** [review]
Thanks 👍

**Comment by wborn** [comment]
There seems to be a merge conflict now in the gather-external-docs-v3 build, see:

https://ci.openhab.org/view/Documentation%20(3.x)/job/gather-external-docs-v3/409/console

**Comment by ecdye** [comment]
> There seems to be a merge conflict now in the gather-external-docs-v3 build, see:
> 
> https://ci.openhab.org/view/Documentation%20(3.x)/job/gather-external-docs-v3/409/console

I think that is because the those images are pulled from an external repo and they are different now, we can revert just those openHABian images, as I optimized them in the openHABian repo anyway.

**Comment by Confectrician** [comment]
We should remove them here completely, when they are pulled from the external repository anyway.
That should prevent us from conflicts in the future.

I already tried to fix the conflict with a local manual build but my java setup is producing some errors which blocks me from that currently.

**Comment by fwolter** [comment]
Pretty cool! I wasn't aware of that algorithm. I'll add the command to the logo documentation PR.

**Pull request merged**
