### PR TITLE
[Enhancement] - Simplify local builds to lower bar for beginners #2215

### PR DESCRIPTION
**Pull request by pgfeller**
... opened a PR here as well - as I would like to see what the pipeline will do with the proposed changes.

This PR allows a more easy way of building the openHAB website. It is now as simple as that:

```
nvm install 16
# ...
$ nvm use 16
Now using node v16.20.2 (npm v8.19.4)
$ npm install
# ...
$ npm run serve
# ...
Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/)
```

requires

```
[node =16.20.1](https://nodejs.org/en)
[ruby >=3.0.2](https://www.ruby-lang.org/en/). -> (even works with ruby 2.6.10...)
[Python >= 3.10.12](https://www.python.org/) 
```

See the readme for details.

### CODE REVIEW

**Comment by pgfeller** [comment]
@stefan-hoehn As expected this has problems with the pipeline - most likely of the changed node version; but that's another new area. I'll try to have a look.

**Comment by pgfeller** [comment]
@stefan-hoehn I would appreciate your comment on the changes and maybe you can test them locally (do you have access to a draft PR)? I'll next finish the docu (remove the footer) and then, if the changes are reasonable, have a look how the CI/CD works ...

**Comment by pgfeller** [comment]
@stefan-hoehn 
Hi Stefan,

I experimented a bit with netlify - and it seems that it is enough to change the node version to 16 - then the docu seems to build:

https://65b9541a996c4a3450d5a2f2--pgfeller.netlify.app/docs/

My test setup is for sure not perfect - as e.g. the redirection to the docs is not there yet - but I think it is a good proof that the proposed changes do not completely break the build 🙂.

But to do all proper checks for the PR a contributor with enough rights needs to change the netlify config for to use node 16 to see if the CI/CD check pass.

**Comment by stefan-hoehn** [comment]
@Confectrician @kaikreuzer @ghys 

Your help would be highly appreciated here because I don't know how I can access netlify for the changes. Can we have session to show it to me?

**Comment by stefan-hoehn** [comment]
@pgfeller Patrik I seem to have now access to netlify, so we can give it try. However, as I am not experienced with netlify, I may not see any settings. Maybe we do a remote session together and try to get it done together.  Just send me a personal message via the openHAB community to schedule something.

**Comment by pgfeller** [comment]
@stefan-hoehn The sidebar changes introduced in main indeed had an impact on this branch - after the re-base things stopped working on my machine as well ➡️ I did some changes and it looks better now ... but I do not fully understand yet if the configuration changes I made for vuepress (especially the include patterns) will have a negative impact when the docu if it is integrated into the webpage (I'll have a look into that ...). 

If you have time it would be interesting if this version now builds locally on your machine (with node 16) - I'll setup the thingy on a windows machine - then we'll know if it works on linux, mac & windows.

**Comment by pgfeller** [comment]
@stefan-hoehn - I did the test on the windows machine. Some (very) minor adjustments were required - but then it runs as well. I propose not to include those adjustments in this PR - but to create a new issue for the windows local build, to keep the changes as small and incremental as possible (I'll do the issue once this PR is merged).

image

➡️ I'll resolve the merge conflict next - I would appreciate if a senior/expert (@Confectrician @kaikreuzer @ghys) could have a look if my change of the vuepress config (especially the glob patterns) will have a negative impact on the full webpage build - or if it still works. I would like to close this PR if possible to  address the windows local build issue next (including some docu on how to setup the necessary environment). It will probably take a long time until I understand the full concept of the integrated page build (but I've started to look into this) - and would like to avoid this delay. The idea is, that docu contributors can preview their changes locally without knowledge of the entire system and to give them a more convenient way to do so as soon as possible - so they can concentrate on content. 

@stefan-hoehn Please consider to grant me enough rights to assign doc repository issues to me - so that I can properly link things. Another question - is there a place for such discussions as we have in this review; or is there a better place for this that would be preferred?

**Comment by pgfeller** [comment]
> Another question - is there a place for such discussions as we have in this review; or is there a better place for this that would be preferred?

@stefan-hoehn:

Hope you have sunny weather as well 🌞. In my opinion it would be an improvement if strategy discussion could be done in a different place to keep the PR review cleaner and more focused to the change at hand.

What to do think, would this feature maybe have the potential to provide a place to discuss about technology, framework and other changes that could improve the experience outside of PRs:

[GitHub Discussions](https://docs.github.com/en/discussions/quickstart)

**Comment by stefan-hoehn** [comment]
Yes, it makes sense to discuss the topics we have here. AFAIK we don't use "Github-Discussions". To my knowledge there is also no setting that allows you to assign tickets to yourself without giving you all the rights that maintainers have. Just ping me and let me know that an issue should be assigned to yourself and I'll take care of it asap.

How far have you come with this? Did you get to run the website build as well locally, so we know that this change here has no negative side effect?

**Comment by pgfeller** [comment]
> How far have you come with this? Did you get to run the website build as well locally, so we know that this change here has no negative side effect?

Not as fast as fast is I would have liked ... - but that's normal doing SW development 😉. The problem is, that the stack used to build the docu uses some deprecated stuff that is no longer available on recent systems. I've opened the following issue on the webpage repo:

https://github.com/openhab/website/issues/452

➡️ Please assign it to me - I've figured out most of it out already:
```bash
rvm install "ruby-2.4.3" -C --with-openssl-dir=/opt/openssl-1.1.1q
Required ruby-2.4.3 is not installed.
To install do: 'rvm install "ruby-2.4.3"'
ruby-2.4.3 - #removing src/ruby-2.4.3..
Checking requirements for ubuntu.
Requirements installation successful.
Installing Ruby from source to: /home/pgfeller/.rvm/rubies/ruby-2.4.3, this may take a while depending on your cpu(s)...
ruby-2.4.3 - #downloading ruby-2.4.3, this may take a while depending on your connection...
ruby-2.4.3 - #extracting ruby-2.4.3 to /home/pgfeller/.rvm/src/ruby-2.4.3.....
ruby-2.4.3 - #configuring..................................................................
ruby-2.4.3 - #post-configuration..
ruby-2.4.3 - #compiling.........................................................................................................................................................................-
ruby-2.4.3 - #installing...........
ruby-2.4.3 - #making binaries executable..
ruby-2.4.3 - #downloading rubygems-3.0.9
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  865k  100  865k    0     0  2284k      0 --:--:-- --:--:-- --:--:-- 2289k
No checksum for downloaded archive, recording checksum in user configuration.
ruby-2.4.3 - #extracting rubygems-3.0.9.....
ruby-2.4.3 - #removing old rubygems........
ruby-2.4.3 - #installing rubygems-3.0.9................................................................
ruby-2.4.3 - #gemset created /home/pgfeller/.rvm/gems/ruby-2.4.3@global
ruby-2.4.3 - #importing gemset /home/pgfeller/.rvm/gemsets/global.gems..........................................................
ruby-2.4.3 - #generating global wrappers........
ruby-2.4.3 - #gemset created /home/pgfeller/.rvm/gems/ruby-2.4.3
ruby-2.4.3 - #importing gemsetfile /home/pgfeller/.rvm/gemsets/default.gems evaluated to empty gem list
ruby-2.4.3 - #generating default wrappers........
ruby-2.4.3 - #adjusting #shebangs for (gem irb erb ri rdoc testrb rake).
Install of ruby-2.4.3 - #complete 
Ruby was built without documentation, to build it run: rvm docs generate-ri
```

But here as well - we need at least do document the steps to avoid that contributors that would like to add content get frustrated by the environment.

**Comment by pgfeller** [comment]
@stefan-hoehn ping 🙂

I'm online for the next hour - so if you would like to give it a try I'm available. We can also do a call if you like.

**Comment by stefan-hoehn** [comment]
Sorry, I missed that. Would you be available for a call now?

**Comment by pgfeller** [comment]
Yes ... please send me the link 👍

**Comment by stefan-hoehn** [comment]
See community PM

**Review by stefan-hoehn — APPROVED** [review]
Great improvement, Kudos!

**Pull request merged**
