### PR TITLE
Add logo section to dev documentation

### PR DESCRIPTION
**Pull request by fwolter**
I'd like to add a sentence about licensing. Do one need to ask the company for permission adding the logo or is that covered by the LICENSE file?

### CODE REVIEW

**Comment by Confectrician** [comment]
From my view we should at least add a disclaimer for this.
Most of the bigger vendors have guidelines for this.

I have left out the pixometer logo, when adding my binding, because i was not able to get a valid statement from the vendor.

**Comment by Confectrician** [comment]
Hey @fwolter maybe we should adapt the requirements, when @ecdye finished the svg icon tests.
Currently it is lookiung pretty good and we may can provide svg icons too, so no need to limit it to png files.

**Comment by fwolter** [comment]
I added the SVG format and also @ecdye's zopflipng command.

**Comment by Confectrician** [comment]
Currently we have a limit to png files indeed, but i am not yet sure if this was for a reason.
I am trying to evaluate this and then finalize here.

**Comment by Confectrician** [comment]
Hey @fwolter i am a bit behind my plans currently and svg won't be possible that fast.
I would suggest that we remove the svg part again for now and then bring this into the "next" and current version docs.

I think we are holding back too much useful information just for the svg part.

Do you agree?

**Comment by fwolter** [comment]
Yes, sure. I thought it was already possible. I removed the SVG reference.

**Review by Confectrician — APPROVED** [review]
Thanks 👍

**Pull request merged**
