### PR TITLE
Corrected default behavior for group functions

### PR DESCRIPTION
**Pull request by triller-telekom**
Signed-off-by: Stefan Triller <stefan.triller@telekom.de>

### CODE REVIEW

**Comment by ThomDietrich** [comment]
Thanks for your addition! Looks good ;)
Please give me a few days to bring this in line with #250 I'll get back to you soon.

**Comment by triller-telekom** [comment]
Since there were a couple of bugs reported regarding group functions, we defined the behavior to be reproducible, see https://github.com/eclipse/smarthome/pull/3314

**Comment by ThomDietrich** [comment]
@triller-telekom sorry for the delay.
After #250 and #404 I'd be ready to merge yours. Would you please resolve the conflict in your PR (or open a new one, whatever is easier for you).

**Comment by triller-telekom** [comment]
I have just resolved the conflicts, squashed my 2 commits and force pushed them onto this PR.

**Comment by ThomDietrich** [comment]
Thanks!!

**Pull request merged**
