### PR TITLE
Factor OH1 add-on docs into site

### LINKED ISSUE #280: Incorporate OH1 docs and re-factor add-ons section
I am working on a PR to refactor the add-on pages to be generated and linked per source (esh, oh2, oh1) so name clashes don't happen and choices are clearer.  See also https://github.com/openhab/openhab1-addons/pull/5029

### PR DESCRIPTION
**Pull request by watou**
and filter lists by source and install status.  

Fixes #280

Signed-off-by: John Cocula <john@cocula.com> (github user: watou)

### CODE REVIEW

**Comment by ThomDietrich** [comment]
Well you have been busy!! 🎉  That looks amazing! And that's just from the sources, I didn't even deploy it yet. I'll look at the visual results tomorrow, please let me know what I should look out for, are there any aspects you are unsure about?

Thanks for the contribution!

**Comment by watou** [comment]
Thanks @ThomDietrich!  I have https://github.com/openhab/openhab1-addons/pull/5056 in the queue to fix some formatting in the OH1 add-ons.  The row hiding/showing from checkboxes can get out of sync, but the effort to make it perfect just seemed like too much effort. 😄 

As features are added to either add-on repo, or moved to legacy, the categorisation will be updated on the next `./update.sh`.  I would be very happy to have a thorough review, thanks!

These screenshots match the PR:

bindings-1

bindings-2

actions

persistence

**Comment by AngelosF** [comment]
The screenshots look awesome!  Great stuff @watou !

**Comment by ThomDietrich** [comment]
Looks great indeed. One request I have right away is regarding the file pom.xml you already layed your hand on. Could you please add a few things to these lines:

```
readme.write("---\nlayout: documentation\n---\n\n{% include base.html %}\n\n" + readme.text)
```

1. `...documentation\ntitle: " + label + " - Bindings"`, [example](https://raw.githubusercontent.com/openhab/openhab-docs/gh-pages/installation/index.md)
2. Something simliar to this before `readme.text`:
```html
\n<!-- Attention authors: Do not edit directly. Please add your changes to the appropriate source repository -->\n
```
3. (If possible) please add an additional front matter (e.g. "source") directly pointing to the repository file as a full URL. This will be helpful in the above case and for an "Improve this article" button I was thinking about adding.

**Comment by watou** [comment]
> ...documentation\ntitle: " + label + " - Bindings", example

I looked at that last night, but the [Groovy code that renames the readmes](https://github.com/openhab/openhab-docs/pull/284/files#diff-600376dffeb79835ede4a0b285078036R330) does not yet know the label.  The renaming process would have to be reworked to first sniff out the title from the markdown, and then do the rest of the process.  I will see if there is a way that isn't just crazy.

> (If possible) please add an additional front matter (e.g. "source") directly

Great idea.  I will try to capture any other possibly relevant metadata for the front matter.

**Comment by watou** [comment]
Added title to the YAML, was too easy after all.  Not much more metadata can be added to the front matter without jumping through hoops because it was lost at earlier stages.  Constructing the correct edit link to the source README.md for editing would be pretty messy (but not impossible).  Let's leave that until its need is clear?

**Comment by ThomDietrich** [comment]
Understood. Regarding the "need": The idea is to easily allow/encourage a user to contribute. That could be done by opening an issue or a PR.

Now if the full URL is not easily available for *the button* it would be enough to have the URL of the base repository the file came from. That would be a good hint already AND I could easily build the button to create an issue like [this](https://github.com/openhab/openhab2-addons/issues/new?title=[Astro]%20README%20-%20...&body=I%20want%20to%20contribute). Would that be something you can add easily AND un-messy?

Thanks for adding the title! Did you forget about the comment (Nr2 above)?

**Comment by watou** [comment]
> Did you forget about the comment (Nr2 above)?

No, I missed it entirely!  last commit added it.

> it would be enough to have the URL of the base repository the file came from

Even the source repo of the file is lost by the time this bit of Groovy gets to it.  I'm wary of getting "too clever" in the assembly process, at least until a full re-think is needed.

**Comment by watou** [comment]
I see the need for making similar updates for addons/io.md page contents.  Should I do that in a further PR?

**Comment by ThomDietrich** [comment]
> Even the source repo of the file is lost

Okay, then we are down to the minimal requirement :sweat_smile: Could you please add "source: external" to all of them? Thanks! ;)

addons/io.md: A new PR would be great, let's merge this one as soon as possible. Looking at the result now.

**Comment by watou** [comment]
> Could you please add "source: external" to all of them? Thanks! ;)

Will do.  I will revisit the assembly process in the next PR to see if it can capture more for the front matter.

**Comment by ThomDietrich** [comment]
@watou I found a slightly malformed html for "since 2.x" and a not working mobile view. I also think, the batches (great idea!) would look better side by side. I've created a diff: https://gist.github.com/ThomDietrich/6461de591a1fd687f7951638e57c5e46

2017-02-03 14_00_38-bindings - openhab 2 - empowering the smart home - pale moon

**Comment by ThomDietrich** [comment]
The next thing we will have to take care of, is to ensure every binding description starts with one sentence of binding explanation (get rid of cut sentences as for Alarm Decoder, itemizations as LG TV or images as with LCN)

I would take on the openhab2-addons and check for Kramdown violations in the process.

**Comment by watou** [comment]
Thanks for the diff!  I will add a commit here shortly.

> ensure every binding description starts with one sentence

Some might have already been [improved](https://github.com/openhab/openhab1-addons/pull/5056) since your last ./update.sh.  And the [huge migration from the wiki](https://github.com/openhab/openhab1-addons/pull/5029) took care of many as well.

I will create a PR for any remaining I can spot.

**Comment by ThomDietrich** [comment]
> Some might have already been improved since your last ./update.sh. And the huge migration from the wiki took care of many as well.

Amazing! :tada:

**Comment by ThomDietrich** [comment]
One more question: My motivation for #248 is partly because the font (compare header menu) is not presented well. That's not the case in your screenshots. Did you do any local css changes or do you use special browser settings?

**Comment by ThomDietrich** [comment]
(I just learned that the GitHub diff view hast a line wrap set to 120 characters. Good to know!)

**Comment by watou** [comment]
I've made similar updates to actions.md and persistence.md, as well as adding `source: external` to the YAML of the add-on readme files.

> Updating contents is actually something regularly done by Kai.

I've been on that job over at openhab1-addons but of course good pull requests are welcome from all contributors!

> do you use special browser settings?

Not that I'm aware of!  The font in use appears to be Lato, but I do recall seeing Roboto failing to load a few days ago.  The screenshots are from Chrome on Mac.

**Comment by ThomDietrich** [comment]
>> Updating contents is actually something regularly done by Kai.
>
> I've been on that job over at openhab1-addons but of course good pull requests are welcome from all contributors!

My answer was unclear. I was merely talking about executing ./update.sh regularly. That#s something Kai is doing from time to time.

> The screenshots are from Chrome on Mac.

Could be an explanation. I'm on Windows+Firefox.

> Lato, but I do recall seeing Roboto failing

Yeah... going back to Roboto is part of #248.

**Comment by watou** [comment]
Added PR to clean up several intro paragraphs: https://github.com/openhab/openhab1-addons/pull/5062

**Comment by AngelosF** [comment]
I think that the following belongs here (in this PR... excuse my lack of knowledge of github :))

Extremely small update with regards to 1.x bindings:

I think that the following paragraph:
```
[...], for example the binding name from PaperUI for the MQTT binding is “binding-mqtt1-1.9.x”, the config file you have to create is mqtt.cfg [...]
```

Should be changed to:
```
[...], for example the binding name from PaperUI for the MQTT binding is “binding-mqtt1-1.x”, the config file you have to create is mqtt.cfg [...]
```

**Comment by watou** [comment]
Any remaining comments before merge?

**Comment by ThomDietrich** [comment]
Doesn't seem like it ;)

**Comment by watou** [comment]
I signed off on the first and last commits on that branch -- is signing off every commit required?

**Comment by ThomDietrich** [comment]
I am no expert in that area either but CONTRIBUTING.md says:

> then you just add a line to every git commit message

I could just squash and sign for you but isn't that forgery? We did that with smaller contributions in the past but this PR is everything other than small, I would prefer to stick to the rules. Sorry for the inconvenience.

**Comment by kaikreuzer** [comment]
>  but isn't that forgery? 

As he is specifically confirming that he wants all commits to be considered as signed, I think it is fully ok to squash it and leave his sign-off on the squashed commit. In any case, the "squash merging" lets the maintainer edit and change the commit message, so it is his responsibility to do this on behalf of the contributor to the best of his knowledge.

**Comment by ThomDietrich** [comment]
Understood. Thanks for the clarification @kaikreuzer.

"Let's Roll!" Thanks again @watou for this great addition ;)

**Comment by watou** [comment]
Thanks!  At docs.openhab.org it looks like master wasn't pulled on openhab1-addons.

**Comment by watou** [comment]
Good morning @kaikreuzer @ThomDietrich  -- would it be possible to regenerate the site, first having pulled the latest master branch of openhab1-addons as is normally done in `./update.sh`?  There are a number of problems fixed with the README.md files since the commit that's currently published.  It's disappointing to see the debut of my tens of hours of work on the OH1 documentation be in its current state.  Your attention is very much appreciated.  Regards, John

**Comment by watou** [comment]
It also appears that the current site contents were generated from a version of this PR before it was merged (regardless of commits from _repos/openhab).

**Comment by kaikreuzer** [comment]
Just ran update.sh and pushed the changes - please check if everything that you expect is there now!

**Comment by kaikreuzer** [comment]
Btw, if I might add a comment: I personally think there is far too much empty space in the new list:

screen shot 2017-02-05 at 12 00 34

Could that be condensed again a bit? Also, the alignment does not look nice. I'd prefer the name as well as the description columns to be aligned at the top and not centered.

**Comment by watou** [comment]
The site update looks correct.  Thanks for pushing it.

I will see what can be done to condense the list vertically per your request.  

I do not see any centering here; everything looks left-aligned

screenshot

**Comment by ThomDietrich** [comment]
I believe he was talking about vertical alignment. Better?

grafik

**Comment by kaikreuzer** [comment]
> I believe he was talking about vertical alignment. Better?

Yes, vertical alignment, that's why I asked for aligning at the "top".
Yes, looks imho much better (your first option)!

**Comment by ThomDietrich** [comment]
I would prefer the second. Compare the Astro row. Having both on top doesn't look even

**Comment by kaikreuzer** [comment]
It does not look even, because it isn't. The label and the description both have a different spacing wrt the top ruler.

**Comment by watou** [comment]
See #293

**Pull request merged**
