### PR TITLE
[README.md] Refactoring of the README file

### LINKED ISSUE #720: Refactor Readme.md
Since the docs are generated with vuepress in the future and we are changing the repo structure in #665, we have to adapt the readme file too.

I would wait for the ne generation and resctructuring process to be finished, until we refactor that.
We already could remove the jekyll related stuff to prevent some confusion.

Wdyt?

### PR DESCRIPTION
**Pull request by Confectrician**
Since ther will be many things to change and to discuss,
i wanted to provide a WIP PR so we can directly have a look at adaptions and compare them.

Fixes #720 at some time. 😄 

Signed-off-by: Jerome Luckenbach <github@luckenba.ch>

### CODE REVIEW

**Comment by Confectrician** [comment]
# Discussion please in #720

**Comment by Confectrician** [comment]
Hey @ghys,

I have done some writing, maybe you can have a look at it.
Would be nice to have the readme updated in the nearer future since this PR reflects the new repo structure.

**Comment by ghys** [comment]
@Confectrician thanks! You nailed most of it I think.
Instead of reviewing since I have commit rights I have made further changes directly and (I think) improvements to the file in https://github.com/openhab/openhab-docs/pull/722/commits/6f5bf8af8dfd8e0d3905aa23f28afc1b3068e4e6 - now your turn to have a look 😉

**Comment by Confectrician** [comment]
Looks fine so far.
One question.

You have changed some parts to have more than one sentence per line.
We usually track down to one sentence per line to keep it tracked in git better.

In jekyll this didn't make a difference for the generated website.
Is vuepress different here?
If not i would like to keep it on one line per sentence.

**Comment by ghys** [comment]
> You have changed some parts to have more than one sentence per line.
We usually track down to one sentence per line to keep it tracked in git better.

Sorry, I didn't know that.
Feel free to break down to one sentence per line if you make changes, otherwise I'll do it.

**Comment by Confectrician** [comment]
Will do so.

Anything else from your side?
We can improve that of course later again.
I just wanted to have a quick up to date readme, so that people know what they are looking at.

**Comment by ghys** [comment]
> Anything else from your side?

Not atm - I'm good. I will make updates when I find time to do the "bare-bones VuePress config" in this repo so that we get live updates when working on the docs in master, and Netlify previews.

**Pull request merged**
