### PR TITLE
Added info about version pinning

### PR DESCRIPTION
**Pull request by spacemanspiff2007**
Added version pinning

### CODE REVIEW

**Comment by stefan-hoehn** [comment]
Nice addition (happened to me more than often...) 
Do you mind adding how to unpin the version again?

**Comment by jimtng** [comment]
The command didn't work for me
```
root@bd5ad9a07dd5:/# apt install openhab=4.0.1
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package openhab is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Version '4.0.1' for 'openhab' was not found
```

It worked without specifying the version
```
root@bd5ad9a07dd5:/# cat /etc/apt/sources.list.d/openhab.list
deb [signed-by=/usr/share/keyrings/openhab.gpg] https://openhab.jfrog.io/artifactory/openhab-linuxpkg stable main
root@bd5ad9a07dd5:/# apt install openhab
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  unzip zip
Suggested packages:
  openjdk-17-jre | java17-runtime | java17-runtime-headless | zulu17-jdk | temurin-17-jdk
The following NEW packages will be installed:
  openhab unzip zip
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 104 MB of archives.
After this operation, 116 MB of additional disk space will be used.
Do you want to continue? [Y/n] ^C
```

This works though:
```
root@bd5ad9a07dd5:/# apt-get install openhab=4.0.1-1
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  unzip zip
Suggested packages:
  openjdk-17-jre | java17-runtime | java17-runtime-headless | zulu17-jdk | temurin-17-jdk
The following NEW packages will be installed:
  openhab unzip zip
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 104 MB of archives.
After this operation, 116 MB of additional disk space will be used.
Do you want to continue? [Y/n] ^C
```

**Comment by spacemanspiff2007** [comment]
> The command didn't work for me

That's why I added the command to list all available versions.
How can I make it more clear that you have to check the version before pinning?

**Comment by stefan-hoehn** [comment]
Btw, I guess I misunderstood it, sorry. Is it really about pinning a version or retrieving a particular version?

> sudo apt install openhab=4.0.1

installs openHAB 4.0.1

and what happens if I go for the following afterwards? 

> sudo apt install openhab

Would it still install 4.0.1 (that is what I would understand with "pin") or just get the latest version?

**Comment by spacemanspiff2007** [comment]
@stefan-hoehn 
I am 100% sure any more that my example works as expected. I rephrased to use apt-mark.
If you specify openHAB manually apt should always do the installation.
The idea is to prevent an unexpected upgrade when running ``apt upgrade``.

**Comment by spacemanspiff2007** [comment]
Build fails unrelated

**Comment by stefan-hoehn** [comment]
@spacemanspiff2007 Unfortunately I was off for quite some time. Sorry for that delay!

I finally fixed the related file. Do you mind rebasing and pushing again?

**Review by stefan-hoehn — APPROVED** [review]
Looks good to me but please rebase due to the related issue.

**Pull request merged**
