### PR TITLE
Documentation for IP addon discovery service

### PR DESCRIPTION
**Pull request by andrewfg**
Documentation for IP addon discovery service.

See https://github.com/openhab/openhab-core/pull/4477

Signed-off-by: Andrew Fiddian-Green <software@whitebear.ch>

### CODE REVIEW

**Comment by andrewfg** [comment]
@holgerfriedrich there was no documentation at all for the IP finder service; so I had to write the full doc rather than simply adding the new mac address description; => so perhaps you can check this for me?

**Review by holgerfriedrich — COMMENTED** [review]
Thanks a lot, @andrewfg!

Overall, LGTM. Do you think we should mention the default value for `fmtMac`?

**Review by holgerfriedrich — APPROVED** [review]
LGTM

**Review by stefan-hoehn — APPROVED** [review]
Thx for comprehensive doc! Lgtm.

**Pull request merged**
