### PR TITLE
[luftdateninfo][sensorcommunity] Rename binding

### PR DESCRIPTION
**Pull request by holgerfriedrich**
Rename addon icon due to renaming of the binding. openhab/openhab-addons#15012

However, the icon still needs to be reworked. The old name is part of the logo.

Maybe the project can assist and provide a new logo, e.g. based on https://sensor.community/favicon.png
@pjgueno

### CODE REVIEW

**Comment by stefan-hoehn** [comment]
Like so?

image

or so

image

**Comment by holgerfriedrich** [comment]
Thanks! I think the text needs to be removed or changed to sensor.community. See their website.

But I don't know about copyright, fair use, etc....

**Comment by stefan-hoehn** [comment]
I checked the licenses here: https://sensor.community/de/ (see "legal")
I personally see no issues for using the logo but you may ask in the forum. Then I would recommend to not only change the filename but the logo itself as well. You can find the official logos here: https://sensor.community/de/presskit/

**Review by Confectrician — APPROVED** [review]
Thanks. 👍🏼

**Comment by stefan-hoehn** [comment]
@holgerfriedrich Any news on this regarding my comment?

**Comment by holgerfriedrich** [comment]
No progress, working on a different topic. 
Doc export is anyway blocked by #2085.

Maybe the quick solution would be to delete the obsolete file. I can close this PR.

**Comment by holgerfriedrich** [comment]
@stefan-hoehn I just pushed the delete to remove the icon for luftdateninfo, which is anyway obsolete after renaming of the binding.
Please feel free to close my PR in case you want to upload a new logo in a combined PR.

**Comment by stefan-hoehn** [comment]
Closing PR upon request, don't hesitate a new one later for the renamed binding.

**Comment by holgerfriedrich** [comment]
@stefan-hoehn sorry I think you got me wrong. This PR now just deletes the obsolete file, it can be merged. Binding is already renamed.

The open point is the new logo - this can be a new PR. I just don't want to mess with any legal topics. I don't know about fair use or what is actually allowed to take and upload.

**Review by Confectrician — APPROVED** [review]

**Comment by Confectrician** [comment]
Merging now to clean the outdated logo. :)

**Pull request merged**
