### PR TITLE
Updated develop docs according to spotless maven code formatting plugin

### PR DESCRIPTION
**Pull request by seime**
Related to https://github.com/openhab/openhab-core/issues/935

### CODE REVIEW

**Comment by Confectrician** [comment]
Hey @seime,

Just mention me, when we are ready. :)
Have a nice weekend.

**Comment by seime** [comment]
Depends on https://github.com/openhab/openhab-core/pull/1101

**Comment by cweitkamp** [comment]
Thank you. One comment from my side: If possible I would prefer to not change the numbering of our coding guidelines.

**Comment by seime** [comment]
@Confectrician Ready for review

**Pull request merged**
