### PR TITLE
add androidtv logo

### PR DESCRIPTION
**Pull request by morph166955**
Add logo for the new androidtv binding: https://github.com/openhab/openhab-addons/pull/14282

Signed-off-by: Ben Rosenblum <rosenblumb@gmail.com>

### CODE REVIEW

**Comment by Hilbrand** [comment]
Looks like the logo is larger than the required 512x512. See; https://www.openhab.org/docs/developer/bindings/#add-your-binding-s-logo-to-the-openhab-website

**Comment by morph166955** [comment]
> Looks like the logo is larger than the required 512x512. See; https://www.openhab.org/docs/developer/bindings/#add-your-binding-s-logo-to-the-openhab-website

Sorry, fixed now.  Thank you!

**Comment by Hilbrand** [comment]
Not to put on to much pressure :smile: but now it seems to have lost transparency?

**Comment by morph166955** [comment]
> Not to put on to much pressure 😄 but now it seems to have lost transparency?

LOL I am not a graphics person.  I just threw the original into paint and said "resize".  No clue how to even attempt to do that.

**Comment by Hilbrand** [comment]
I've created a transparent version (tried to do this via GitHub editor, but that creates a new pr. And  I can't seem to create a pull request here to your branch). But the file is here: https://github.com/Hilbrand/openhab-docs/blob/eb77ffc885a51614f09099500b5d6ccc4452defa/images/addons/androidtv.png

**Comment by morph166955** [comment]
Thank you!  I've committed the one you posted.

**Review by Confectrician — APPROVED** [review]
Thanks. 👍🏼

**Comment by maniac103** [comment]
Given https://github.com/openhab/openhab-addons/pull/14282 isn't merged (yet?), wasn't adding the icon a bit premature?

**Comment by Confectrician** [comment]
Don't know how this happened.
I have no strong opinion on keeping or reverting this.
Hopefully it gets merged befor the 4.0 Release so we can simply save double work and leave it as is.

It won't break anything.

**Comment by morph166955** [comment]
It is my sincere hope that the binding is merged into 4.0. It's just pending the review cycle at this point.

**Pull request merged**
