### PR TITLE
Update introduction.md

### PR DESCRIPTION
**Pull request by nostroff**
Replace references to sitemap with page. Pages description row in concepts table could be improved - perhaps "are web site pages generated by openHAB (software) to provide a user interface that presents information and allows interactions.

### CODE REVIEW

**Comment by Confectrician** [comment]
I am not sure, if we should delete Sitemaps completely from the table.
Sitemaps may not be the main UI Interface anymore, but Basic UI and (at least) the Android App are still using sitemaps.

So they are a valid and available approach of building a ui.
Also Sitemaps are not marked as deprecated at any point currently.

**Comment by nostroff** [comment]
The motivation for the change is to align the introduction section with the Main UI. As a newbie, having sitemaps included as a key concept and no mention of the Main UI/pages was a source of confusion.

**Comment by rkoshak** [comment]
> I am not sure, if we should delete Sitemaps completely from the table.
> Sitemaps may not be the main UI Interface anymore, but Basic UI and (at least) the Android App are still using sitemaps.

I think it depends on whether we want sitemaps to be a part of our first impression. That table is not and can not be comprehensive. So are sitemaps part of what we want to be in our first impression? I'd say no, and instead we should point at MainUI Pages instead. I'm not sure the Getting Started Tutorial even mentions sitemaps except in passing. 

That doesn't mean that sitemaps are deprecated or no longer supported or anything like that. It just means that MainUI is what we want to use as a first impression. 

I think the changes made in this PR are reasonable.

**Comment by nostroff** [comment]
Please do not consider the proposed text as being sacred. More than anything, the PR has the perspective of someone new to OpenHAB and tries to be specific/constructive in identifying one area where the documentation can be improved (IMHO).

**Comment by Confectrician** [comment]
Valid points.
Thanks for the discussion. 🙂

**Review by Confectrician — APPROVED** [review]
Thanks. 👍🏼

**Pull request merged**
