### PR TITLE
add description of Ephemeris localization support

### PR DESCRIPTION
**Pull request by Rosi2143**
Add a new section to describe the localization support and how-to 

Signed-off-by: Michael Roßner <Schrott.Micha@web.de>

### CODE REVIEW

**Comment by Rosi2143** [comment]
Signed-off-by: Schrott.Micha Schrott.Micha@web.de

**Comment by Rosi2143** [comment]
Signed-off-by: Schrott.Micha Schrott.Micha@web.de

**Comment by Rosi2143** [comment]
Signed-off-by: Michael Roßner <Schrott.Micha@web.de>

**Comment by Confectrician** [comment]
Hey @Rosi2143,

Thanks for the improvement.
It seems like you are having a hard time with our dco check.
(Sorry for that.)

### First of all
I will override the failed check for this PR. No need for any additional action on your side here.

### DCO Check in general
If your are interested in the solution for your failed dco check, i have written a tutorial which explains how to add the correct statements to make this one pass immediately.
You can find it [here](https://community.openhab.org/t/dco-check-signing-off-with-github-web-editor-explanation/83330?u=confectrician).

Additionally there was a contribution about improving the docs some days ago.
Your can find it [here](https://www.openhab.org/docs/developer/contributing.html#contributing-to-the-documentation).

If there are any questions i am glad to help out. :)

**Pull request merged**
