### PR TITLE
[kermi] add Logo for Kermi Modbus Binding

### PR DESCRIPTION
**Pull request by KaaNee**
Logo for Modbus Kermi Binding.
MR: https://github.com/openhab/openhab-addons/pull/16329

### CODE REVIEW

**Review by stefan-hoehn — COMMENTED** [review]
Did you intentionally leave so much space around the logo?

**Comment by KaaNee** [comment]
@stefan-hoehn No. I took the original from the company. Should it be trimmed to fit better?

**Comment by KaaNee** [comment]
@stefan-hoehn please re-check, trimmed logo borders.
Ok, now ?

**Review by stefan-hoehn — APPROVED** [review]
Yep, thanks.

**Pull request merged**
