### PR TITLE
Add directory /opt/openhab to chown command

### PR DESCRIPTION
**Pull request by tubit**
Hi,

I've just added the missing directory for openhab files within the chown command.

Cheers,
Dennis

### CODE REVIEW

**Comment by ThomDietrich** [comment]
Thank you @tubit!
@rkoshak Looks right to me.

**Comment by rkoshak** [comment]
Thanks! LGTM.

**Comment by ThomDietrich** [comment]
@tubit. Would be great to see more corrections or additions from you.
If you add more than a small fix, please pay attention to the [signing requirement](https://github.com/openhab/openhab-docs/blob/gh-pages/CONTRIBUTING.md#sign-your-work) ;)

**Comment by tubit** [comment]
Hi @ThomDietrich! Thanks, will sign if there is more to come. :)

**Pull request merged**
