### PR TITLE
updated link to snapshot

### PR DESCRIPTION
**Pull request by kaikreuzer**

### CODE REVIEW

**Comment by AngelosF** [comment]
You forgot to sign off your contribution :)
"Signed-off-by: Kai Kreuzer kai@openhab.org"

**Comment by kaikreuzer** [comment]
You are wrong! This was by intention, taking the liberty to make use of the [small patch exception](https://github.com/openhab/openhab-docs/blob/gh-pages/CONTRIBUTING.md#small-patch-exception)! 😛

**Comment by ThomDietrich** [comment]
Hehe :smile: 
@kaikreuzer while we are looking at the Contributing guidelines: Did you know that they also specify to write commit messages in the imperative mood? :stuck_out_tongue:

**Comment by kaikreuzer** [comment]
No, I have never read this line 😇 .

**Pull request merged**
