### PR TITLE
Tutorial: Transfer Getting Started Tutorial from community forum #191

### PR DESCRIPTION
**Pull request by DocFraggle**
Continue with tutorial as we discussed

regards, Christian

### CODE REVIEW

**Comment by DocFraggle** [comment]
@ThomDietrich I added the persistence page for the beginner's tutorial

Regards, Christian

**Comment by ThomDietrich** [comment]
Hey Christian,
The new content looks great!

One general request: Please break your text down to one line per sentence. That will help git better deal with changes. The result on the page will be the same.

Second thing that came to my mind when looking over the tutorial: I think it would be beneficial to reduce the image size. Right now we have full-width images making it hard to recognize and follow the instructions around them. There are two ways to influence image size. If you just want to reduce size, you can do that by adding [ALDs](https://kramdown.gettalong.org/syntax.html#attribute-list-definitions), [examples](https://kramdown.gettalong.org/quickref.html#block-attributes)
If you want to do more complex stuff, it might be easier to use vanilla html. Here is an example for two images that will be next to each other on bigger screens and after each other on smartphones: http://docs.openhab.org/addons/uis/apps/android.html

"http://IP-of-your-machine:8080" is a string in your first article. You need to make it a link explicitly.

Introduce more headers or emphasize **important** words to make the text better readable. (Compare [this](http://docs.openhab.org/tutorials/beginner/configuration.html) with [this](http://docs.openhab.org/installation/rasppi.html)

Please link more. Topics like sitemaps or logging are described elsewhere in more detail. These articles should be linked to.

That's it for today :) Let me know if anything is unclear or you disagree (I'm not the boss here ;) )
Thank you!

**Comment by ThomDietrich** [comment]
Hey Christian, any news from your side?

**Comment by Confectrician** [comment]
Hey @ThomDietrich 

There are 3 conflicts and no action since over a year.
Additionally the sign-off would be missing.

I would have liked to merge and improve this one, but due t the sign-off i think we should close this one.

Wdyt?

**Pull request closed without merging**
