### PR TITLE
Update windows.md

### PR DESCRIPTION
**Pull request by edolis**
updated the installation steps updates specifically required to perform a working install on Windows 10.
-> corrected the JAVA_PATH with the recommended updated Zulu path
-> modified wrapper.conf so that it includes the changes which allow the Windows service to start.
Ref: https://community.openhab.org/t/oh3-installation-service-fails-to-start-cannot-create-java-virtual-machine/110430/17

### CODE REVIEW

**Comment by hmerk** [comment]
@edolis To be inline with our package installation, I would suggest not to have version numbers in the folder name.
Same aplies to other openHAB references.
In earlier discussion, we decided to remove the version on all ocourrances and just use openHAB. This makes the docs future proof for upcoming versions on parts that don‘t change.

**Comment by edolis** [comment]
> @edolis To be inline with our package installation, I would suggest not to have version numbers in the folder name.
thanks @hmerk and please be patient, it's my first time on GIT and I am not able to navigate comfortably yet.
What folder name are you referring to?

**Comment by hmerk** [comment]
Yes please, running 2 versions parallell would need two different java versions, only for experienced users I guess...

**Comment by edolis** [comment]
okie, let me fix it... can please someone explain me how to sign? with the -s but.. where? In the comment box of the commit?

**Comment by hmerk** [comment]
Ah, you are using a GUI version for git. I have no clue then, cause I develop on linux and us git console command.
But on Windows, you als should be able to use git on console, command would be
git commit -s -m „commit message“
Otherwise you shoul check the docs for your git client and search for sign-off.

**Comment by rkoshak** [comment]
You will need to go back and amend the commits already created to include the signoff. I have no idea how to accomplish that. @Confectrician, any ideas? I know how to do it from the command line (i think) but that doesn't help here. I found https://docs.github.com/en/free-pro-team@latest/github/committing-changes-to-your-project/changing-a-commit-message but that seems excessive. :-|

**Comment by edolis** [comment]
Ahhhhh, I'm getting crazy.
I have installed Github desktop, I have got the changes made, I have created a key, I cannot get Github desktop to sign. What an absolute pain in the neck.

**Comment by Confectrician** [comment]
Don't worry too much about the signoff^^
I can override it if necessary.

Anyway here is a general explanation how to handle this with different ui's i have written some time ago:

https://community.openhab.org/t/dco-check-signing-off-with-github-web-editor-explanation/83330?u=confectrician

**Pull request closed without merging**
