### PR TITLE
Update docs for openhab2-addons repo rename

### PR DESCRIPTION
**Pull request by wborn**
Updates the documentation for the rename of the openhab2-addons GitHub repository to openhab-addons.

### CODE REVIEW

**Comment by Confectrician** [comment]
Hi @wborn and thanks.

Are you aware of #1114 ?
I think this is duplicated content, at least in some parts.

**Comment by Confectrician** [comment]
Maybe you can add a a pr against @Hilbrand s repo/branch, when somethings missing over there.

**Comment by wborn** [comment]
OK I'll close this one. I looked into the PR list but didn't expect a more than 2 weeks old PR to lingering there. ;-)

**Comment by Confectrician** [comment]
>but didn't expect a more than 2 weeks old PR to be lingering there. ;-)

I am currently working on fixing the website build and adapt the background scripts too for the introduced 2.5.x branching.
That's the reason for postponing this one so far. :)

**Pull request closed without merging**
