### PR TITLE
Fix `Number:<dimension>` item type

### PR DESCRIPTION
**Pull request by mueller-ma**
`<` and  `>` need to be escaped to be visible.

### CODE REVIEW

**Comment by mueller-ma** [comment]
On https://deploy-preview-2020--openhab-docs-preview.netlify.app/ I cannot find the page I edited. Instead there's a nearly duplicate page, which contains the same issue: https://github.com/openhab/openhab-docs/blob/main/concepts/items.md

**Comment by mueller-ma** [comment]
I updated both pages, should be fine now.

**Comment by stefan-hoehn** [comment]
I can see your change on https://deploy-preview-2020--openhab-docs-preview.netlify.app/docs/concepts/items.html and LGTM.

**Comment by Confectrician** [comment]
@mueller-ma can you give me a hint which page you have edited befor which was not available?

I am not able to follow this, since you **force pushed** everything again.

**Comment by mueller-ma** [comment]
[This page ](https://www.openhab.org/docs/configuration/items.html)isn't available in the preview posted by netlify above: https://deploy-preview-2020--openhab-docs-preview.netlify.app/configuration/items.html

**Comment by Confectrician** [comment]
I know, that we are are moving and copying different parts during the build, but i am currently not aware of what is happening in the configuration part exactly. i will try to dig into whats happening here.

**Pull request merged**
