### PR TITLE
Add NUT Binding logo

### PR DESCRIPTION
**Pull request by florian-h05**
@Confectrician This adds the missing network UPS tools (NUT) Binding logo.

### CODE REVIEW

**Review by wborn — COMMENTED** [review]
Did you manually scale this up? It looks pixelated.

**Comment by florian-h05** [comment]
Yes, I’ve scaled this one up to meet the 512x512 px described in the docs.

**Comment by wborn** [comment]
I would think that only applies to downscaling so the images are not unnecessarily big. It's already upscaled by the browser when necessary which will result in the same pixelated look without transferring unnecessary data.

**Comment by florian-h05** [comment]
Okay, I‘ll then put the original version here.

**Review by Confectrician — APPROVED** [review]

**Pull request merged**
