### PR TITLE
[Linux] Replace legacy statement

### PR DESCRIPTION
**Pull request by ThomDietrich**
Signed-off-by: Thomas Dietrich <Thomas.Dietrich@tu-ilmenau.de>

### CODE REVIEW

**Comment by watou** [comment]
Does https://github.com/openhab/openhab-docs/pull/311/commits/af8ba4eaeab506aaa33e6d49104bde43a5ebfd27 relate to the description of this PR?

**Comment by ThomDietrich** [comment]
Hmmm yes, the PR title is just a bit misleading looking at what "legacy" means in relation to add-ons
https://github.com/koalaman/shellcheck/wiki/SC2006

**Comment by watou** [comment]
Ah thanks!  Different context for use of word "legacy."  Muchas gracias.

**Comment by ThomDietrich** [comment]
Thanks for looking at this @watou. I've chosen a better squash commit message I hope ;)

**Pull request merged**
