### PR TITLE
Extra fields for addon discovery in addon.xml

### PR DESCRIPTION
**Pull request by andrewfg**
**Documentation of new fields in `addon.xml`**

In OpenHAB core there is a PR [#3865](https://github.com/openhab/openhab-core/pull/3865) which adds extra fields to the addon.xml file so that addons may be discovered during the initial setup of OH and thus be suggested to be installed during setup. This PR is the documentation for the additional fields.

**Publish updated XML schema with new fields on OpenHAB Web Server**

The extra fields introduced in PR [#3865](https://github.com/openhab/openhab-core/pull/3865) are self documented in the XML schema file `addon-1.0.0.xsd` in 'org.openhab.core.addon', so the new version of this file needs to be manually copied to the OH web server as well.

Signed-off-by: Andrew Fiddian-Green <software@whitebear.ch>

### CODE REVIEW

**Comment by stefan-hoehn** [comment]
@andrewfg Did you see the failing markdown errors?

**Comment by andrewfg** [comment]
> Did you see the failing markdown errors?

I did now. There seems to be also some errors not related to this PR..

**Comment by stefan-hoehn** [comment]
> > Did you see the failing markdown errors?
> 
> I did now. There seems to be also some errors not related to this PR..

Yep, I am on the others as they are preventing all other PRs to be merged as well. 
And can you please ping me when the related PR #3865 is merged?

**Comment by andrewfg** [comment]
> ping me when the related PR #3865 is merged

I will do that.

**Comment by stefan-hoehn** [comment]
@andrewfg I was able to rebase the branch, so it based on the latest version of the files that prevented you to build. Please pull your repo accordingly before you continue.

**Comment by andrewfg** [comment]
@stefan-hoehn do I need to do anything more on this PR to ensure it gets merged?

https://github.com/openhab/openhab-core/pull/3806#issuecomment-1839075966

**Pull request merged**
