### PR TITLE
[rules-dsl] Fixes #561: Add File Name section - add warning regarding UNDERSCORE in filename

### LINKED ISSUE #561: RULES: Use of the UNDERSCORE (_) is not permitted in RULE file names.
On the RULES page it should be mentioned that you can not use the UNDERSCORE _ character in filenames of rules.  Using the character causes OH to skip the file and does not provide any feedback in the logs.

I spent many nights reviewing the code to see why the rules were not firing, my syntax was correct but the file name prevented OH from processing the file.

If any other characters are not permissible in the file name outside of the basic (/?&%...etc) then they should be listed on the rules page as well.

### PR DESCRIPTION
**Pull request by bgilmer77**
Signed-off-by: Brad Gilmer <brad@gilmer.tv> (github: bgilmer77)

### CODE REVIEW

**Comment by bgilmer77** [comment]
Help please - obviously using the CLI I have made an error.  It seems that the commit related to introduction.md got mixed with the commit I made for rules-dsl.  I have made mistakes before trying to back out commits, so I will wait for @ThomDietrich and/or @Confectrician to give me some suggestions on the best way to fix this.

FWIW, this has been a pretty steep learning curve.  I really appreciate your help in getting up and running so that I can contribute to the project.

**Comment by bgilmer77** [comment]
I believe I have figured this out, but please comment @ThomDietrich or @Confectrician .  I am guessing I created the branch for this commit while I was on the gilmer-intro1 branch.  I should have been on the gh-pages branch when I created the branch for this PR.  Please let me know if this is what it looks like to you, and let me know the best way to fix this.

**Comment by Confectrician** [comment]
>  I should have been on the gh-pages branch when I created the branch for this PR.

Exactly.
I always check if i am on gh pages when creating a new branch.

My Workflow for handling the fork is this:
1. Keep gh-pages in my fork always up to date with the openhab/openhab-docs repo.
2. Only checkout new branches from that gh-pages repo.
3. Only update other branches when needed. (For example when merge conflicts appear.)

To be honest i dont know how to cut out this commit now.
I know you can cut out the las commit or several last commits, but i dont know how to cut out one special commit while leaving the others as they are.

**Comment by bgilmer77** [comment]
@Confectrician I am happy to redo the entire PR.  My workflow would be:
-  Delete this PR
-  Delete the branch on GitHub
-  Delete the branch on my local Git

Does that sound right?  Something tells me I have to reset the HEAD back before this commit before I delete the branch.

**Comment by Confectrician** [comment]
You can delete those branches and check out a new branch from gh-pages this time.

Tip from my side:
Copy the whole rules-dsl file somewhere, so you dont have to type everything again.

Second tip:
Since it is unclear if we need this improvement, you can wait with adding a new PR, until we have finished the corresponding issue discussion.

**Comment by bgilmer77** [comment]
@Confectrician , thank you for the tips, and I agree.  I am going to back up my local rules-dsl file, close this PR, and then backout the commit from my repo.  I will leave things like that until the discussion on the issue comes to a conclusion.

**Comment by bgilmer77** [comment]
I am closing this PR for two reasons:
1) The commit was created from a branch other than the `gh-pages` branch - this is an error.
2) The issue this PR addresses is not resolved, and there is some question about whether there really is an issue with the underscore character.

Once #561 is resolved, I will create a new, clean PR to address it, if needed.

**Pull request closed without merging**
