### PR TITLE
Synology Java prereq and installation

### PR DESCRIPTION
**Pull request by hphde**
Signed-off-by: Heinz Peter Hippenstiel <github.hph@xoxy.net> @hphde
I prefer this

### CODE REVIEW

**Comment by ThomDietrich** [comment]
@hphde could you please sign your work!? Thanks! https://github.com/openhab/openhab-docs/blob/gh-pages/CONTRIBUTING.md

**Comment by hphde** [comment]
Done @ThomDietrich

**Comment by ThomDietrich** [comment]
Your mail address is needed as well I'm afraid

**Comment by hphde** [comment]
How to get people spammed. If this "email format" is not accepted I withdraw my request - sorry.

**Comment by watou** [comment]
The signoff should be on the commit message, not the PR comment.  The format should be

```
Signed-off-by: Heinz Peter Hippenstiel <remove-nospam.hph@j0t.de> (github: hphde)
```

No issue I'm aware of with your actual email address.

You can `git commit --amend` with the above added, followed by a `git push -f`.

I *think* this is right advice, but not sure how to handle when submitting changes only via the GitHub web UI.

**Comment by ThomDietrich** [comment]
Hello @hphde, first because I didn't say it before: Thanks for your contribution!
These signing off rules are quite important for the development parts of openHAB, where intellectual property violations, especially in the binding development area, could become a real problem for openHAB as an open source platform.

@kaikreuzer do you see an option to address spamming concerns? I would accept the Sign-off-by in the description of the Pull Request as long as it is squashed and amended in the process!? In documentation we shouldn't overdo it.

**Comment by kaikreuzer** [comment]
> @kaikreuzer do you see an option to address spamming concerns?

I had these concerns as well in the beginning, but after thousands of commits by now on Github, I still do not have any spam problem. So I think it isn't a huge risk (I also never heard ANY complaint from ANY contributor about that).

I'd be fine with @watou's suggestion to use something like `<remove-nospam.hph@j0t.de>`.

**Comment by hphde** [comment]
@kaikreuzer it was my suggestion to provide the remove-nospam prefix :+1: - I have an issue providing private email addresses to the public. It's easy to create new ones on the fly anyway - so I don't understand the benefit having that in the signoff. But I guess you already had tons of this discussion in the past ...

I do understand the rational behind property violations. But isn't there an easier way as requested by now? Can't you create a code-of-conduct-certificate page and let everyone just sign this one once? The git handle is your trail anyway. No?

Besides it's likely that I am not going to submit much more in this repository than this page I did. I will not follow and download a complete documentation server stack. This overhead is a killer for a quick submission like I have.

**Comment by kaikreuzer** [comment]
@hphde I didn't invent copyright laws nor intellectual property rights. As I am not a lawyer, I didn't even dare to come up with this process myself, but rather adopted what other well-managed projects are doing - this specific section e.g. [from Docker](https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work). Note that the sign-off "tradition" actually comes from the Linux kernel and was introduced after the [SCO lawsuits](http://stackoverflow.com/a/1962112) if you remember them.

Note that you can add the sign-off through Github editor as well - simply add it as a last line in the commit message and all is well. So once you know how to do it, it really isn't much overhead.

**Comment by ThomDietrich** [comment]
Merged.
Thank you @hphde.
Hope to see more additions from you! Best Regards

**Pull request merged**
