### PR TITLE
[developer-bindings] getRemovalGracePeriodSeconds for mDNS discovery

### PR DESCRIPTION
**Pull request by andrewfg**
This updates the developer guide for binding developers to reflect the changes that will be made in https://github.com/openhab/openhab-core/pull/2635

Signed-off-by: Andrew Fiddian-Green <software@whitebear.ch>

### CODE REVIEW

**Comment by Confectrician** [comment]
I have subscribed to the dependency pr and will include this, when it gets merged.

**Comment by andrewfg** [comment]
@jlaur -- for info...

**Comment by Confectrician** [comment]
Hey @andrewfg 

The core pr has been merged but i have seeon some discussion going on the addons repo regarding the same topic.
Are we safe to merge or should we wait a bit for possible upocoming edits here?

**Comment by andrewfg** [comment]
Please wait..

**Comment by andrewfg** [comment]
^
Ok, I think it is clean now.

**Comment by Confectrician** [comment]
OK. Thanks for the feedback.

**Review by Confectrician — APPROVED** [review]

**Pull request merged**
