### PR TITLE
Coding guidelines updated (proposal)

### PR DESCRIPTION
**Pull request by kubawolanin**
Signed-off-by: Kuba Wolanin <hi@kubawolanin.com>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Thanks, wanted to add that as well! I'll do some further recommendations regarding logging and include your lines in it - will first do a PR against https://www.eclipse.org/smarthome/documentation/development/guidelines.html.

**Comment by kaikreuzer** [comment]
FTR: https://github.com/eclipse/smarthome/pull/2996

**Comment by kubawolanin** [comment]
Thx @kaikreuzer ! Closing this one

**Comment by kaikreuzer** [comment]
Also copied it over to http://docs.openhab.org/developers/development/guidelines.html#e-logging (I guess you have seen it). I hope it is along the lines you would expect.

**Comment by kubawolanin** [comment]
It'll definintely make code review easier ;-) Cheers!

**Pull request closed without merging**
