### PR TITLE
Add "Designing dashboard interfaces with HABPanel"

### PR DESCRIPTION
**Pull request by ghys**
This adds a new article describing HABPanel in more detail
in the Configuration section of the user manual.

As discussed in:
https://github.com/openhab/org.openhab.ui.habpanel/pull/159

Signed-off-by: Yannick Schaus <habpanel@schaus.net>

### CODE REVIEW

**Comment by ThomDietrich** [comment]
I fear we had a misunderstanding. Instead of creating a copy of the article here manually we should have the [update script](https://github.com/openhab/openhab-docs/blob/gh-pages/update.sh) fetch the latest version of the document from your repository. This way you'll not have to push changes to the docs repository every time you want to improve the documentation.

The process would be the same as with the eclipse smarthome concept files, see [here](https://github.com/openhab/openhab-docs/blob/gh-pages/pom.xml#L59-LL76).

**Comment by ghys** [comment]
Err, totally misunderstood that 😄 
I figured since there were already `habmin.md` and `paperui.md` files in the `configuration` folder the most straightforward thing to do was simply to add `habpanel.md` in there. But it makes sense to keep the doc in the original repo as well.

So it appears the entire `doc` directory of the HABPanel repo is already be copied to `_uis/oh2/uis/org.openhab.ui.habpanel/doc` (by [this](https://github.com/openhab/openhab-docs/blob/gh-pages/pom.xml#L232)); I fear I don't understand what to do next to include it in the navigation?

**Comment by ThomDietrich** [comment]
Hey, right! I overlooked that fact, even easier. In this case the docs article(s) just have to be copied over, just like the concept files from eclipse smarthome. I'm currently traveling but after I'm back I wanted to basically do the same thing with the openHABian documentation. I can include whatever's needed for your documentation then. Okay with you?

**Comment by ghys** [comment]
Sure! I wasn't sure where to copy them exactly (in `configuration`?) so I figured I'd rely on you instead to figure out how to proceed ;)
Safe travels!

**Comment by ThomDietrich** [comment]
@ghys I'll be traveling over the weekend.
I've been staling for a long time but will hopefully look into this next week.
I've already decided how to do it, see #62

**Comment by ghys** [comment]
@ThomDietrich great!
I'll make sure the docs are up-to-date in the HABPanel repo in the meantime.

**Pull request closed without merging**
