### PR TITLE
Update guidelines.md

### PR DESCRIPTION
**Pull request by jossuar**
Corrected link to ESH.xml

Signed-off-by: Georgios Moutsos <georgios.moutsos@gmail.com>

### CODE REVIEW

**Comment by jossuar** [comment]
I'm not sure if the changed link to download the ESH.xml file works correctly.

**Comment by Confectrician** [comment]
It doesn't work.

@ghys 
It looks like vuepress can't or won't handle xml files or at least this special one.
I can't acces it from this preview or the live build, alltough it should be there since it is definetely in the repo.

Can you have a look?

**Comment by Confectrician** [comment]
I have added the direct raw link to github for now until we have a long term solution or i have found the reason for the missing xml file processing.

When the preview works i will merge this one.

**Comment by ghys** [comment]
> It doesn't work.
> 
> @ghys
> It looks like vuepress can't or won't handle xml files or at least this special one.
> I can't acces it from this preview or the live build, alltough it should be there since it is definetely in the repo.
> 
> Can you have a look?

Sorry @Confectrician - I was in holidays and missed that!

**Comment by Confectrician** [comment]
No problem.
I thought it was important to have a working solution meanwhile.

We can revert that at an time, when the problem is addressed.

**Pull request merged**
