### PR TITLE
Sample solutions of the OSGi tasks.

### PR DESCRIPTION
**Pull request by m-memova**
My colleague, @kirilAtan has been working on these sample solutions. I gave him a little help to finish them. Some of the merged solutions are slightly changed. If you have any questions, don't hesitate to ask.

Signed-off-by: Mihaela Memova <mihaela.memova@musala.com>

### CODE REVIEW

**Comment by hakan42** [comment]
There are some *.class-files in the pull request. Should they not be removed first?

**Comment by m-memova** [comment]
You are right, I thought I've been removed them. Thank you :-)

**Comment by m-memova** [comment]
Thank you, @hakan42 ! I removed the *.class files.

**Comment by ThomDietrich** [comment]
@m-memova your paths seem to be wrong. @kirilAtan commited to `_sample_code/osgi_codings_tasks/bundles/...`.
See: https://github.com/openhab/openhab-docs/pull/113/files

On a side note: I don't know your workflow but it seems to me you missed to add *.class to your `.gitignore`?

**Comment by m-memova** [comment]
Thank you, @ThomDietrich. And sorry for the mistake. I updated the PR.

**Comment by ThomDietrich** [comment]
Thank you!

**Pull request merged**
