### PR TITLE
[fmiweather] logo for FMI Weather binding

### PR DESCRIPTION
**Pull request by ssalonen**
Logo for FMI Weather binding.

Use of FMI logo is not allowed. But we can use the "open data" logo as proposed in this PR.

License details in https://ilmatieteenlaitos.fi/avoin-data-lisenssi (in Finnish):

> Ilmatieteen laitoksen avoimen datan yhteydessä voi hyödyntää yllä olevaa logoa. Ilmatieteen laitoksen logoa avoimen datan tuotteissa ei saa käyttää.

Freely translated

> In the context of open data of the Meteorological Institute, the logo above can be utilized. The Meteorological Institute logo for open data products must not be used.

Pending https://github.com/openhab/openhab2-addons/pull/6329

Signed-off-by: Sami Salonen <ssalonen@gmail.com>

### CODE REVIEW

**Comment by Confectrician** [comment]
Hey @ssalonen ,

It seems there is no WIP needed.
I would add a dependency label and we can merge this one, when the binding pr got merged too.

A short poke is all that's needed and i will push the button then.

BR
Jerome

**Comment by Confectrician** [comment]
Edited startpost to reflect new pending PR

Pending https://github.com/openhab/openhab2-addons/pull/6329

**Comment by ghys** [comment]
Note: changed the base branch to `2.5.x` which is the default for now, and will appear on the production website.
`master` is now the branch for openHAB 3.x docs.

@openhab/documentation-maintainers 
Once this is merged to `2.5.x` please remember to merge (for example, cherry-pick the commit) this to `master` as well if appropriate.
See https://github.com/openhab/openhab-docs/issues/1133 for details.

**Comment by ssalonen** [comment]
Please merge, related binding is now merged as well

**Pull request merged**
