### PR TITLE
Add support for tab containers

### PR DESCRIPTION
**Pull request by ghys**
Uses https://github.com/pskordilakis/vuepress-tabs.

Related to https://github.com/openhab/website/issues/183.

Update dependencies.

Signed-off-by: Yannick Schaus <github@schaus.net>

### CODE REVIEW

**Comment by ghys** [comment]
@openhab-5iver @Confectrician could you have a look at
https://deploy-preview-1023--openhab-docs-preview.netlify.com/docs/configuration/jsr223.html#just-testing-the-tabs
and check whether or not it fits your requirements for https://github.com/openhab/website/issues/183?
One functionality which doesn't appear possible is to switch all tabs on the same page at once when you click one...
If you approve this addition I will remove the test paragraph before merging.

**Comment by openhab-5iver** [comment]
I won't be able to look from my computer for a couple hours, but this is from Firefox on mobile...

Screenshot_20190803-084941

... not very tabby, but SO much better than nothing... thank you! Sphinx uses [Pygments](http://pygments.org/) for code highlighting, so I'd setup a style that mimics VS Code.

**Comment by ghys** [comment]
Heh, indeed, on desktops it looks better. Since there'll be room in most cases to display the tabs inline even on phones, it makes sense to cancel the responsive stuff; could probably be done by tweaking or overriding the provided styles.

**Comment by openhab-5iver** [comment]
Finally got to look at this (Firefox desktop)... and this is fantastic! The outer border is a little lighter (IMO too light), but it looks identical to what you get with Sphinx. Can it do nested tabs? Please merge!

I realize this is really a separate topic, but what is being used for the code highlighting? It would be nice if it looked more like VS Code. [Here's the Pygment style](https://github.com/openhab-scripters/openhab-helper-libraries/blob/master/Sphinx/_styles/vscode.py) I'd mentioned... it's not perfect, but might help with the colors.

**Comment by ghys** [comment]
> what is being used for the code highlighting

https://highlightjs.org/static/demo/

I can't seem to find the style VuePress uses by default, but there seem to be a VS style as well.

**Comment by ghys** [comment]
Ok should be good for merging. (minus the test paragraph)
I'll have to add an equivalent PR to the website side.

**Comment by openhab-5iver** [comment]
Looks good on mobile now too!

**Comment by Confectrician** [comment]
I had a quick look on desktop and its fantastic. 🙂

**Comment by ghys** [comment]
Ok I have nothing more to add, let's merge this then.
You can work on PRs here and get the preview with tabs, but don't merge them until the website is done. :)

**Pull request merged**
