### PR TITLE
Added basic 404 page.

### LINKED ISSUE #30: Custom 404 page
If you open a non existing page like http://docs.openhab.org/somepage/ a 404 page with GitHub branding is shown. This should be replaced with a OH branded one.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/35273598-custom-404-page?utm_campaign=plugin&utm_content=tracker%2F37358380&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F37358380&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by BClark09**
Added a page which notifies the user that the page couldn't be found, offers the same navigation links as the main page and suggests that the user helps create the page if it should exist.

Also converted the main-page bar to an _include template to prevent duplicating the same html code in different pages.

Closes #30 

Signed-off-by: Ben Clark <ben@benjyc.uk>

### CODE REVIEW

**Comment by BClark09** [comment]
image

**Comment by ThomDietrich** [comment]
Amazing! :) Could you add the `title` front matter to both pages, while you are at it?

See [random example](https://raw.githubusercontent.com/openhab/openhab-docs/gh-pages/installation/linux.md)

**Comment by BClark09** [comment]
No problem, all set! :smile:

**Comment by ThomDietrich** [comment]
And go. :clap:

**Pull request merged**
