### PR TITLE
Fixed some smaller defects

### PR DESCRIPTION
**Pull request by MHerbst**
See https://github.com/openhab/openhab-docs/pull/277#issuecomment-277338674

### CODE REVIEW

**Comment by AngelosF** [comment]
I may be wrong... but I think that you may want to change to EN the first part of the link also:

```
<a href="http://tools.google.com/dlpage/gaoptout?hl=de">http://tools.google.com/dlpage/gaoptout?hl=en</a>.
```

**Comment by MHerbst** [comment]
Oh ... shit

**Comment by AngelosF** [comment]
I don't know why, but when I view the privacy.md ([View](https://github.com/MHerbst/openhab-docs/blob/31b31ce38354c7207ea01051bdcd40adb4a3d188/privacy.md)) all anchors appear and work correctly... 
but this is not true for the imprint.md ([View](https://github.com/MHerbst/openhab-docs/blob/31b31ce38354c7207ea01051bdcd40adb4a3d188/imprint.md))

I can't identify the error...

I hope that I am not bugging you too much :) :)

**Comment by AngelosF** [comment]
I think that I found it:
The line:
```
{% comment %}<!-- Based on http://www.openhab.org/imprint.html -->
```

is missing the {% endcomment %} which appears all the way to the end of the file

**Comment by MHerbst** [comment]
Thank you for your help. It seems I was a bit too fast :-(

**Comment by AngelosF** [comment]
I double checked all 3 files and they LGTM now 👍

**Comment by ThomDietrich** [comment]
Thanks @MHerbst for the contribution and thanks to @AngelosF for helping with the review!

@AngelosF which open issue will you challenge next? 😜

**Pull request merged**
